element: Beryllium
isotope: 0
variant: 0
num_protons: 8
nuclets:
  1:
    position: 1
    geometry: icosahedron
    num_protons: 8
    num_nuclear_electrons: 6
    protons:
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: false
      5:
        present: true
      6:
        present: true
      7:
        present: false
      8:
        present: true
      9:
        present: false
      10:
        present: true
      11:
        present: false
      12:
        present: true

