name: 18 0 Argon
element: Argon
isotope: 0
numProtons: 20
nuclets:
  N0:
    state: backbone-initial
    numProtons: 12
    numInnerElectrons: 6
  N00:
    state: neutral
    attachAngle: 1
    numProtons: 4
    numInnerElectrons: 2
  N01:
    state: neutral
    attachAngle: 1
    numProtons: 5
    numInnerElectrons: 2

