name: 0 0 Final Backbone
element: carbon
isotope: 0
variant: 0
numProtons: 12
nuclets:
  N0:
    state: initial
    numProtons: 20
    numInnerElectrons: 6
    protons: [0,1,2,3,4,5,6,7,8,9,10,11]
    electrons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true

