name: 06 0 Carbon 12
element: Carbon
isotope: 0
variant: 0
numProtons: 12
nuclets:
  N0:
    state: carbon
    numProtons: 12
    numInnerElectrons: 6
    protons: [0,1,2,3,4,5,6,7,8,9,10,11]
    electrons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true


