name: 09 0 Flourine
element: flourine
isotope: 0
variant: 0
numProtons: 19
nuclets:
  N0:
    state: initial
    numProtons: 18
    numInnerElectrons: 6
    protons: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    electrons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true

