name: 24 0 Illegal
element: Illegal
isotope: 0
numProtons: 24
nuclets:
  N0:
    state: backbone-final
    numProtons: 12
    numInnerElectrons: 6
  N00:
    state: backbone-final
    attachAngle: 2
    numProtons: 12
    numInnerElectrons: 6
  N01:
    state: backbone-initial
    attachAngle: 5
    numProtons: 12
    numInnerElectrons: 6

