name: 12 0 Magnesium
element: Magnesium
isotope: 0
numProtons: 24
nuclets:
  N0:
    state: final
    numProtons: 12
    protons: [0,1,2,3,4,5,6,7,8,9,10,11]
    numInnerElectrons: 6
    nuclets:
      N00:
        state: lithium
        attachAngle: 3
        numProtons: 6
        numInnerElectrons: 3
        protons: [1, 4, 5, 3, 11, 9]
      N01:
        state: lithium
        attachAngle: 3
        numProtons: 6
        numInnerElectrons: 3
        protons: [1, 4, 5, 3, 11, 9]

