name: 08 0 Oxygen
element: Oxygen
isotope: 0
variant: 0
numProtons: 16
nuclets:
  N0:
    state: initial
    numProtons: 16
    numInnerElectrons: 6
    protons: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    electrons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true

