name: Hexahedron
geoGroups:
  protons:
    components:
      framework:
        shape: hexahedron
        scale: 1.72
        protons:
          0:
            type: default
          1:
            type: default
          2:
            type: default
          3:
            type: default
          4:
            type: default
          5:
            type: default
          6:
            type: default
          7:
            type: default
  hexa:
    components:
      solid:
        shape: hexahedron
        scale: 1.30
        wireframe: true
        faces: true
      vertexids:
        shape: hexahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: hexahedron
        scale: 1.3
        faceids: true

