name: Octahedron
geoGroups:
  protons:
    rotation:
      y: 90
    geometries:
      framework:
        shape: octahedron
        scale: 1.38
        protons:
          0:
            type: default
          1:
            type: default
          2:
            type: default
          3:
            type: default
          4:
            type: default
          5:
            type: default
  octa:
    rotation:
      y: 90
    geometries:
      solid:
        shape: octahedron
        scale: 1.20
        wireframe: true
        faces: true
      vertexids:
        shape: octahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: octahedron
        scale: 1.3
        faceids: true

