name: Dodecahedron
geoGroups:
  protons:
    geometries:
      framework:
        shape: dodecahedron
        scale: 2.8
        protons:
          0:
            type: default
          1:
            type: default
          2:
            type: default
          3:
            type: default
          4:
            type: default
          5:
            type: default
          6:
            type: default
          7:
            type: default
          8:
            type: default
          9:
            type: default
          10:
            type: default
          11:
            type: default
          12:
            type: default
          13:
            type: default
          14:
            type: default
          15:
            type: default
          16:
            type: default
          17:
            type: default
          18:
            type: default
          19:
            type: default
  dodeca:
    geometries:
      solid:
        shape: dodecahedron
        scale: 1.7
        wireframe: true
        faces:
          0:
            type: valence
            attach: -left
            location: top-front
          1:
            type: isotope
            attach: deca-left
            location: top-middle
          2:
            type: isotope
            attach: deca-right
            location: top-middle
          3:
            type: valence
            attach: deca-right
            location: top-rear
          4:
            type: valence
          5:
            type: valence
            attach: deca-left
            location: top-rear
          6:
            type: valence
            attach: deca-left
            location: bottom-front
          7:
            type: valence
          8:
            type: valence
            attach: deca-right
            location: bottom-rear
          9:
            type: valence
            attach: deca-right
            location: top-front
          10:
            type: valence
          11:
            type: isotope
          12:
            type: isotope
      vertexids:
        shape: dodecahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: dodecahedron
        scale: 1.3
        faceids: true

# icosa:
#   rotation:
#     y: 90
#   geometries:
#     solid:
#       shape: icosahedron
#       scale: 1.7
#       wireframe: true
#       faces: true
#     vertexids:
#       shape: icosahedron
#       scale: 1.3
#       vertexids: true
#     faceids:
#       shape: icosahedron
#       scale: 1.5
#       faceids: true


