name: icosalet
position: {x: 0, y: 0, z: 0}
rotation: {x: 0, y: 0, z: 0}
allowmove: false
geoGroups:
  protons:
    allowrotate: false
    rotation:
      y: 31.7
    geometries:
      framework:
        shape: icosahedron
        scale: 2.05
        protons:
          - left
          - marker
          - default
          - default
          - default
          - default
          - default
          - default
          - default
          - default
          - default
          - right
  icosa:
    allowrotate: false
    rotation:
      y: 31.7
    geometries:
      solid:
        shape: icosahedron
        scale: 1.39
        wireframe: true
        faces: true
      axes:
        shape: icosahedron
        axes:
          scale: 3
          vertices:
            - [0, 11]
            - [1,  8]
            - [2,  9]
            - [3, 10]
            - [4,  6]
            - [5,  7]
      vertexids:
        shape: icosahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: icosahedron
        scale: 1.3
        faceids: true

  dodeca:
    allowrotate: false
    rotation:
      y: -58.3
    geometries:
      solid:
        shape: dodecahedron
        scale: 1.27
        wireframe: true
        faces: true
      axes:
        shape: dodecahedron
        axes:
          scale: 3
          vertices:
            - [0, 13]
            - [1, 12]
            - [2, 11]
            - [3, 10]
            - [4, 14]
            - [5, 17]
            - [6, 18]
            - [7, 19]
            - [8, 15]
            - [9, 16]
      vertexids:
        shape: dodecahedron
        scale: 1.3
        vertexids: true
      faceids:
        shape: dodecahedron
        scale: 1.5
        faceids: true

  octa:
    allowrotate: true
    rotation: {y: -58.3}
    geometries:
      framework:
        shape: octahedron
        scale: 1.25
        electrons: 
          - default
          - default
          - default
          - default
          - default
          - default
        wireframe: true
      axes:
        shape: octahedron
        axes:
          scale: 3
          vertices:
            - [0, 1]
            - [2, 3]
            - [4, 5]
      vertexids:
        shape: octahedron
        scale: 1.3
        vertexids: true
