name: Neutral
weight: 2
order:
position: {x: 0, y: 0, z: 0}
rotation: {x: 0, y: 0, z: 0}
allowmove: false
geoGroups:
  protons:
    geometries:
      framework:
        shape: neutral
        protons:
          0:
            type: neutral
          1:
            type: neutral
          3:
            type: neutral
          5:
            type: neutral
          9:
            type: isotope

