name: Lithium
weight: 3
position: {x: 0, y: 0, z: 0}
rotation: {x: 0, y: 0, z: 0}
allowmove: false
geoGroups:
  protons:
    allowrotate: false
    geometries:
      framework:
        shape: decahedron
        scale: 1.698
        scaleHeight: 1.05
        protons:
          0:
            type: lithium
          1:
            type: lithium
          2:
            type: lithium
          3:
            type: lithium
          4:
            type: lithium
          5:
            type: lithium
          6:
            type: lithium
  deca:
    allowrotate: false
    geometries:
      solid:
        shape: decahedron
        scale: 1.70
        scaleHeight: 1.25
        wireframe: true
        attachFaces: true
        faces:
          0:
            type: valence
            attach: deca-left
            location: top-front
          1:
            type: isotope
            attach: deca-left
            location: top-middle
          2:
            type: isotope
            attach: deca-right
            location: top-middle
          3:
            type: valence
            attach: deca-right
            location: top-rear
          4:
            type: valence
          5:
            type: valence
            attach: deca-left
            location: top-rear
          6:
            type: valence
            attach: deca-left
            location: bottom-front
          7:
            type: valence
          8:
            type: valence
            attach: deca-right
            location: bottom-rear
          9:
            type: valence
            attach: deca-right
            location: top-front
      axes:
        shape: decahedron
        axes:
          scale: 3
          vertices:
            - [0, 1]
      vertexids:
        shape: decahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: decahedron
        scale: 1.3
        faceids: true

