name: Neutral
weight: 2
order:
allowmove: false
geoGroups:
  protons:
    geometries:
      framework:
        shape: neutral
        protons:
          0:
            type: neutral
          1:
            type: neutral
          3:
            type: neutral
          5:
            type: neutral
          9:
            type: neutral

