name: Backbone Final
weight: 8 
geoGroups:
  protons:
    geometries:
      framework:
        shape: backbone
        particleids: proton
        protons:
          0:
            type: grow
          1:
            type: grow
          2:
            type: grow
          3:
            type: grow
          4:
            type: valence
          5:
            type: valence
          6:
            type: valence
          7:
            type: valence
          8:
            type: polar
          9:
            type: polar
          10:
            type: polar
          11:
            type: polar
        tetrahedrons:
          0:
            vertices: [1, 14, 0, 13]
          1:
            vertices: [13, 0, 1, 7]
          2:
            vertices: [7, 13, 0, 12]
          3:
            vertices: [14, 1, 0, 4]
          4:
            vertices: [4, 0, 14, 15]
          5:
            vertices: [12, 0, 7, 9]
          6:
            vertices: [15, 4, 0, 8]
          7:
            vertices: [3, 18, 2, 17]
          8:
            vertices: [17, 2, 3, 5]
          9:
            vertices: [5, 17, 2, 16]
          10:
            vertices: [18, 3, 2, 6]
          11:
            vertices: [6, 2, 18, 19]
          12:
            vertices: [16, 2, 5, 8]
          13:
            vertices: [19, 6, 2, 9]
      protonids:
        shape: backbone
        scale: 1.9
        protonids: true
  icosa:
    allowrotate: false
    rotation:
      y: 90
    geometries:
      solid:
        shape: icosahedron
        scale: 1.37
        wireframe: true
        attachFaces: true
        faces:
          0:
            type: valence
          1:
            type: isotope
          2:
            type: isotope
          3:
            type: valence
          4:
            type: valence
          5:
            type: valence
          6:
            type: valence
          7:
            type: valence
          8:
            type: valence
          9:
            type: valence
          10:
            type: valence
          11:
            type: isotope
          12:
            type: isotope
          13:
            type: valence
          14:
            type: valence
          15:
            type: valence
          16:
            type: valence
          17:
            type: valence
          18:
            type: valence
          19:
            type: valence
      axes:
        shape: icosahedron
        axes:
          scale: 3
          vertices:
            - [0, 3]
            - [1, 2]
            - [4, 7]
            - [5, 6]
            - [8, 11]
            - [9, 10]
      vertexids:
        shape: icosahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: icosahedron
        scale: 1.3
        faceids: true

  dodeca:
    allowrotate: false
    geometries:
      solid:
        shape: dodecahedron
        scale: 1.31
        wireframe: true
        faces: true
      axes:
        shape: dodecahedron
        axes:
          scale: 3
          vertices:
            - [0, 13]
            - [1, 12]
            - [2, 11]
            - [3, 10]
            - [4, 14]
            - [5, 17]
            - [6, 18]
            - [7, 19]
            - [8, 15]
            - [9, 16]
      vertexids:
        shape: dodecahedron
        scale: 1.3
        vertexids: true
      faceids:
        shape: dodecahedron
        scale: 1.5
        faceids: true

  octa:
    allowrotate: true
    geometries:
      framework:
        shape: octahedron
        scale: 1.25
        electrons: 
          - default
          - default
          - default
          - default
          - default
          - default
        wireframe: true
      axes:
        shape: octahedron
        axes:
          scale: 3
          vertices:
            - [0, 1]
            - [2, 3]
            - [4, 5]
      vertexids:
        shape: octahedron
        scale: 1.3
        vertexids: true
