name: Boron
weight: 3
geoGroups:
  protons:
    rotation:
      y: 90
    geometries:
      framework:
        scale: 1.9
        shape: boron
        protons:
          0:
            type: grow
          1:
            type: grow
          2:
            type: grow
          3:
            type: grow
          4:
            type: valence
          5:
            type: valence
          6:
            type: valence
          7:
            type: valence
          8:
            type: neutral
          9:
            type: polar
          10:
            type: polar
          11:
            type: polar
