name: Lithium
weight: 3
geoGroups:
  protons:
    rotation:
      y: 90
    geometries:
      framework:
        scale: 1.9
        shape: lithium
        protons:
          1:
            type: grow
          3:
            type: grow
          4:
            type: valence
          5:
            type: valence
          9:
            type: polar
          10:
            type: polar
          11:
            type: polar
  deca:
    alignyaxis:
      vertices: [9,10]
      attachPt: -.400
      rotatey: 18
    geometries:
      solid:
        shape: decahedron
        scale: 1.70
        scaleHeight: 1.25
        wireframe: true
        attachFaces: true
        faces:
          0:
            type: valence
            attach: deca-left
            location: top-front
          1:
            type: isotope
            attach: deca-left
            location: top-middle
          2:
            type: isotope
            attach: deca-right
            location: top-middle
          3:
            type: valence
            attach: deca-right
            location: top-rear
          4:
            type: valence
          5:
            type: valence
            attach: deca-left
            location: top-rear
          6:
            type: valence
            attach: deca-left
            location: bottom-front
          7:
            type: valence
          8:
            type: valence
            attach: deca-right
            location: bottom-rear
          9:
            type: valence
            attach: deca-right
            location: top-front
      axes:
        shape: decahedron
        axes:
          scale: 3
          vertices:
            - [0, 1]
      vertexids:
        shape: decahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: decahedron
        scale: 1.3
        faceids: true

