name: Base
description: 'Initial style set'
filepath: config/style/platonic_solids/base.yml
styles:
  ambient--color:
    defaultValue: '#4f4f4f'
    type: color
  camera--perspective:
    defaultValue: 20
    type: range
  camera--position--x:
    defaultValue: 0
    type: position
  camera--position--x--az-slider:
    defaultValue: 200
    type: position
  camera--position--y:
    defaultValue: 2000
    type: position
  camera--position--y--az-slider:
    defaultValue: 1500
    type: position
  camera--position--z:
    defaultValue: -2000
    type: position
  camera--position--z--az-slider:
    defaultValue: -1500
    type: position
  dodeca--rotation--x:
    defaultValue: 0
    type: rotation
  dodeca--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  dodeca--rotation--y:
    defaultValue: 0
    type: rotation
  dodeca--rotation--y--az-slider:
    defaultValue: 0
    type: rotation
  dodeca--rotation--z:
    defaultValue: 0
    type: rotation
  dodeca--rotation--z--az-slider:
    defaultValue: 0
    type: rotation
  dodeca--scale:
    defaultValue: 1
    type: range
  dodecaFaceid--opacity:
    defaultValue: 0
    type: range
  dodecaFaceids--scale:
    defaultValue: 1
    type: range
  dodecaFaces--color:
    defaultValue: '#0065bc'
    type: color
  dodecaFaces--opacity:
    defaultValue: '0.5'
    type: range
  dodecaVertexid--opacity:
    defaultValue: 0
    type: range
  dodecaVertexids--scale:
    defaultValue: 1
    type: range
  dodecaWireframe--color:
    defaultValue: '#0088ff'
    type: color
  dodecaWireframe--linewidth:
    defaultValue: 4
    type: range
  dodecaWireframe--opacity:
    defaultValue: 1
    type: range
  electron--radius:
    type: range
    defaultValue: 5
  hexa--rotation--x:
    defaultValue: 0
    type: rotation
  hexa--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  hexa--rotation--y:
    defaultValue: 0
    type: rotation
  hexa--rotation--y--az-slider:
    defaultValue: 0
    type: rotation
  hexa--rotation--z:
    defaultValue: 0
    type: rotation
  hexa--rotation--z--az-slider:
    defaultValue: 0
    type: rotation
  hexa--scale:
    defaultValue: 1
    type: range
  hexaFaceid--opacity:
    defaultValue: 0
    type: range
  hexaFaceids--scale:
    defaultValue: 1
    type: range
  hexaFaces--color:
    defaultValue: '#aa00aa'
    type: color
  hexaFaces--opacity:
    defaultValue: '0.59'
    type: range
  hexaVertexid--opacity:
    defaultValue: 0
    type: range
  hexaVertexids--scale:
    defaultValue: 1
    type: range
  hexaWireframe--color:
    defaultValue: '#ff00ff'
    type: color
  hexaWireframe--linewidth:
    defaultValue: 4
    type: range
  hexaWireframe--opacity:
    defaultValue: 1
    type: range
  icosa--rotation--x:
    defaultValue: 0
    type: rotation
  icosa--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  icosa--rotation--y:
    defaultValue: 0
    type: rotation
  icosa--rotation--y--az-slider:
    defaultValue: 0
    type: rotation
  icosa--rotation--z:
    defaultValue: 0
    type: rotation
  icosa--rotation--z--az-slider:
    defaultValue: 0
    type: rotation
  icosa--scale:
    defaultValue: 1
    type: range
  icosaFaceid--opacity:
    defaultValue: 0
    type: range
  icosaFaceids--scale:
    defaultValue: 1
    type: range
  icosaFaces--color:
    defaultValue: '#d10000'
    type: color
  icosaFaces--opacity:
    defaultValue: '0.5'
    type: range
  icosaVertexid--opacity:
    defaultValue: 0
    type: range
  icosaVertexids--scale:
    defaultValue: 1
    type: range
  icosaWireframe--color:
    defaultValue: '#ff0000'
    type: color
  icosaWireframe--linewidth:
    defaultValue: 4
    type: range
  icosaWireframe--opacity:
    defaultValue: 1
    type: range
  octa--rotation--x:
    defaultValue: 0
    type: rotation
  octa--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--y:
    defaultValue: 0
    type: rotation
  octa--rotation--y--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--z:
    defaultValue: 0
    type: rotation
  octa--rotation--z--az-slider:
    defaultValue: 0
    type: rotation
  octa--scale:
    defaultValue: 1
    type: range
  octaFaceid--opacity:
    defaultValue: 0
    type: range
  octaFaceids--scale:
    defaultValue: 1
    type: range
  octaFaces--color:
    defaultValue: '#d5d50f'
    type: color
  octaFaces--opacity:
    defaultValue: '0.56'
    type: range
  octaVertexid--opacity:
    defaultValue: 0
    type: range
  octaVertexids--scale:
    defaultValue: 1
    type: range
  octaWireframe--color:
    defaultValue: '#ffff00'
    type: color
  octaWireframe--linewidth:
    defaultValue: 4
    type: range
  octaWireframe--opacity:
    defaultValue: 1
    type: range
  plane--color:
    defaultValue: '#252125'
    type: color
  plane--depth:
    defaultValue: 1200
    type: range
  plane--opacity:
    defaultValue: 1
    type: range
  plane--position--x:
    defaultValue: 0
    type: position
  plane--position--x--az-slider:
    defaultValue: 0
    type: position
  plane--position--y:
    defaultValue: -200
    type: position
  plane--position--y--az-slider:
    defaultValue: -200
    type: position
  plane--position--z:
    defaultValue: 0
    type: position
  plane--position--z--az-slider:
    defaultValue: 0
    type: position
  plane--rotation--x:
    defaultValue: 0
    type: rotation
  plane--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  plane--rotation--y:
    defaultValue: -180
    type: rotation
  plane--rotation--y--az-slider:
    defaultValue: -180
    type: rotation
  plane--rotation--z:
    defaultValue: 1
    type: rotation
  plane--rotation--z--az-slider:
    defaultValue: 1
    type: rotation
  plane--width:
    defaultValue: 1400
    type: range
  proton--opacity:
    defaultValue: '0.56'
    type: range
  proton--radius:
    type: range
    defaultValue: 50
  proton--scale:
    defaultValue: 1
    type: range
  proton-default--color:
    defaultValue: '#979797'
    type: color
  renderer--color:
    defaultValue: '#056538'
    type: color
  spotlight-1--color:
    defaultValue: '#885555'
    type: color
  spotlight-1--position--x:
    defaultValue: -500
    type: position
  spotlight-1--position--x--az-slider:
    defaultValue: -500
    type: position
  spotlight-1--position--y:
    defaultValue: 800
    type: position
  spotlight-1--position--y--az-slider:
    defaultValue: 800
    type: position
  spotlight-1--position--z:
    defaultValue: -500
    type: position
  spotlight-1--position--z--az-slider:
    defaultValue: -500
    type: position
  spotlight-2--color:
    defaultValue: '#558855'
    type: color
  spotlight-2--position--x:
    defaultValue: 800
    type: position
  spotlight-2--position--x--az-slider:
    defaultValue: 800
    type: position
  spotlight-2--position--y:
    defaultValue: 800
    type: position
  spotlight-2--position--y--az-slider:
    defaultValue: 800
    type: position
  spotlight-2--position--z:
    defaultValue: -200
    type: position
  spotlight-2--position--z--az-slider:
    defaultValue: -200
    type: position
  spotlight-3--color:
    defaultValue: '#555588'
    type: color
  spotlight-3--position--x:
    defaultValue: -500
    type: position
  spotlight-3--position--x--az-slider:
    defaultValue: -500
    type: position
  spotlight-3--position--y:
    defaultValue: 800
    type: position
  spotlight-3--position--y--az-slider:
    defaultValue: 800
    type: position
  spotlight-3--position--z:
    defaultValue: -500
    type: position
  spotlight-3--position--z--az-slider:
    defaultValue: -500
    type: position
  tetra--rotation--x:
    defaultValue: 0
    type: rotation
  tetra--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  tetra--rotation--y:
    defaultValue: 0
    type: rotation
  tetra--rotation--y--az-slider:
    defaultValue: 0
    type: rotation
  tetra--rotation--z:
    defaultValue: 0
    type: rotation
  tetra--rotation--z--az-slider:
    defaultValue: 0
    type: rotation
  tetra--scale:
    defaultValue: 1
    type: range
  tetraFaceid--opacity:
    defaultValue: 0
    type: range
  tetraFaceids--scale:
    defaultValue: 1
    type: range
  tetraFaces--color:
    defaultValue: '#64b564'
    type: color
  tetraFaces--opacity:
    defaultValue: '0.59'
    type: range
  tetraVertexid--opacity:
    defaultValue: 1
    type: range
  tetraVertexids--scale:
    defaultValue: 1
    type: range
  tetraWireframe--color:
    defaultValue: '#00ee00'
    type: color
  tetraWireframe--linewidth:
    defaultValue: 4
    type: range
  tetraWireframe--opacity:
    defaultValue: 1
    type: range
