name: Atom Builder
static:
  reset:
#   title: Mouse
    controls:
      camera--reset:           ['Reset Camera',      'button']
      style--reset:            ['Reset Style',      'button']

      hr1: ['null', hr]
hidden:
  nuclet:
    title:               Nuclet Hidden
    controls:
      nuclet--state:
        - State
        - radios
        - initial
        -
          initial: 2-3 Initial
          neutral: 4-5 Neutral
          lithium: 6 Lithium
          beryllium: 8 Beryllium
          boron: 10 Boron
          carbon: 11 Carbon
          backbone-initial: Initial Backbone
          backbone-final: Final Backbone
      nuclet--attachAngle:     ['Angle',          'range',   1,  [1, 5, 1]]
      nuclet--attachProton:    ['Attach Pt',      'radios',  10, {10: '10', 11: '11'}]
#     nuclet--grow-label:      ['Grow Points',    'label']
#     nuclet--grow-0:          ['&nbsp;&nbsp;0',  'html',    '--']
#     nuclet--grow-1:          ['&nbsp;&nbsp;1',  'html',    '--']
      nuclet--delete:          ['Delete',         'button']
styler:
  nucleus:
    title:               Nucleus
    controls:
#     hr1:                     [ null,            'hr']
      nucleus--loadlabel:      ['Select nucleus', 'header']
      nucleus--selectyml:      [ null,            'selectyml', 'carbon.yml', 'nucleus', 'config/nucleus',       'atomizer.ajax_yml_load']
      nucleus--information:    [ null,            'container']
      hr2:                     [ null,            'hr']
      nucleus--nuclets-label:  ['Nuclets',        'header']
      nucleus--nuclets:        [ null,            'container']
      hr3:                     [ null,            'hr']
      nucleus--new:            ['Save New',       'button']
      nucleus--overwrite:      ['Overwrite',      'button']
      nucleus--reset:          ['Reset',          'button']
      nucleus--delete:         ['Delete',         'button']
  axes:
    title:               Axes
    controls:
      hr0:                        [ null,              'hr']
      attachLines--label:         ['Attach Axes',      'header']
      attachLines--opacity:       ['Opacity',          'range',    0, [0, 1, .01]]
      attachLines--scale:         ['Scale',            'range',    4, [0, 6, .01]]
      attachLines--linewidth:     ['Linewidth',    'range',        1, [0, 5, .1]]
      hr1:                        [ null,              'hr']
      nuclet--label:              ['Nuclet',           'header']
      nucletAxes--opacity:        ['Opacity',          'range',    0, [0, 1, .01]]
      nucletAxes--scale:          ['Scale',            'range',    4, [0, 6, .01]]
      nucletAxes--linewidth:      ['Linewidth',    'range',        1, [0, 5, .1]]
      hr2:                        [ null,              'hr']
      nucletInnerAxes--label:     ['Inner Nuclet Shell',     'header']
      nucletInnerAxes--opacity:   ['Opacity',          'range',    0, [0, 1, .01]]
      nucletInnerAxes--scale:     ['Scale',            'range',    3, [0, 6, .01]]
      nucletInnerAxes--linewidth: ['Linewidth',    'range',        3, [0, 5, .1]]
      hr3:                        [ null,              'hr']
      nucletOuterAxes--label:     ['Outer Nuclet Shell',     'header']
      nucletOuterAxes--opacity:   ['Opacity',          'range',    0, [0, 1, .01]]
      nucletOuterAxes--scale:     ['Scale',            'range',    2, [0, 6, .01]]
      nucletOuterAxes--linewidth: ['Linewidth',    'range',        5, [0, 5, .1]]
  particles:
    title:               Protons, Electrons
    controls:
      proton--label:             ['Protons', 'header']
      proton-default--color:     ['Default',      'color',    '#777777']
      proton-grow--color:        ['Grow',         'color',    '#559999']
      proton-valence--color:     ['Valence',      'color',    '#995599']
      proton-polar--color:       ['Polar',        'color',    '#999955']
      proton-lithium--color:     ['Lithium',      'color',    '#995555']
      proton-newproton--color:   ['New Proton',   'color',    '#555599']
      proton-newneutron--color:  ['New Neutron',  'color',    '#559955']
      proton-vattach--color:     ['Val Attach',   'color',    '#66dd66']
      proton-iattach--color:     ['Isotope',      'color',    '#55dddd']
      proton-ghost--color:       ['ghost',        'color',    '#aa55aa']
      proton--opacity:           ['Opacity',      'range',    .9, [0, 1, .01]]
      protons--scale:            ['Scale',        'range',     1, [0, 3, .01]]

      hr1:                       [ null,          'hr']
      protonVertexid--color:     ['Proton IDs',   'color',    '#ff00ff']
      protonVertexid--opacity:   ['Opacity',      'range',    1, [0, 1, .01]]
      protonVertexid--scale:     ['Scale',        'range',    1,  [0, 3, .01]]

      hr2:                       [ null,          'hr']
      electron--color:           ['Electrons',    'color',    '#ffff33']
      electron--opacity:         ['Opacity',      'range',     1, [0, 1, .01]]
      electron--scale:           ['Scale',        'range',     1, [0, 3, .01]]

  scene:

    title:               Scene
    controls:
      header--camera:          ['Camera',        'header']
      camera--perspective:     ['Perspective',   'range',    25, [1, 90, 1]]
      camera--position:        ['Position',      'position', [0, 0, -1500], [-3000, 3000, 1]]

      hr1:                     [ null, 'hr']
      renderer--color:         ['Background',    'color',    '#fcf3ff']

      hr2:                     [ null, 'hr']
      plane--color:            ['Plane',         'color',    '#cccccc']
      plane--opacity:          ['Opacity',       'range',    1, [0, 1, .01]]
      plane--width:            ['Width',         'range',    1200, [500, 1500, 1]]
      plane--depth:            ['Depth',         'range',    1200, [500, 1500, 1]]
      plane--position:         ['Position',      'position', [0, -200, 0], [-600, 800, 1]]
      plane--rotation:         ['Rotation',      'rotation', [0, -180, 1], [-180, 180, 1]]

  lighting:

    title:               Lighting
    controls:
      ambient--color:          ['Ambient',       'color',    '#777777']
      hr1:                     [ null, 'hr']
      spotlight-1--color:      ['Spotlight 1',   'color',    '#885555']
      spotlight-1--position:   ['Position',      'position', [-500, 800, -500], [-1000, 1000, 1]]
      hr2:                     [ null, 'hr']
      spotlight-2--color:      ['Spotlight 2',   'color',    '#558855']
      spotlight-2--position:   ['Position',      'position', [ 800, 800, -200], [-1000, 1000, 1]]
      hr3:                     [ null, 'hr']
      spotlight-3--color:      ['Spotlight 3',   'color',    '#555588']
      spotlight-3--position:   ['Position',      'position', [-500, 800, -500], [-1000, 1000, 1]]
