name: Platonic Solids
mouse:
styler:
  style:
    title:               Styles
    controls:
      style--reset:            ['Reset Style',      'button']
      hr1:                     [ null,              'hr']
      style--loadlabel:        ['Current Style',    'header']
      style--selectyml:        [ null,              'selectyml', 'base.yml',   'style',   'config/style/builder', 'atomizer.ajax_yml_load']
      hr2:                     [ null,              'hr']
      style--savelabel:        ['Create New Style', 'header']
      style--saveyml:          [ null,              'saveyml',   '',           'style',   'config/style/builder', 'atomizer.ajax_yml_save']

  proton:
    title:               Protons
    controls:
      proton_default--color:   ['Default',      'color',    '#6666dd']
      proton_top--color:       ['Top',          'color',    '#d4af37']
      proton=bottom--color:    ['Bottom',       'color',    '#dd66dd']
      proton-marker--color:    ['Marker',       'color',    '#55dddd']
      proton--opacity:         ['Opacity',      'range',    .9, [0, 1, .01]]
      proton--scale:           ['Scale',        'range',     1, [0, 2, .01]]

  isocahedron:

    title:               Isocahedron
    controls:

      awireframe--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      awireframe--color:       ['Wireframe',    'color',    '#aaffcc']
      awireframe--opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      awireframe--linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      avertexid--label:        ['IDs',          'label']
      avertexid--opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      avertexids--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      aface--color:            ['Faces',        'color',    '#88cccc']
      aface--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      afaceid--label:          ['IDs',          'label']
      afaceid--opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      afaceids--scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      aaxis--color:            ['Axis',         'color',    '#ffbbcc']
      aaxis--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      aaxis--linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]


  dodecahedron:

    title:               Dodecahedron
    controls:
      bwireframe--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      bwireframe--color:       ['Wireframe',    'color',    '#ffdd33']
      bwireframe--opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      bwireframe--linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      bvertexid--label:        ['IDs',          'label']
      bvertexid--opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      bvertexids--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      bface--color:            ['Faces',        'color',    '#88cccc']
      bface--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      bfaceid--label:          ['IDs',          'label']
      bfaceid--opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      bfaceids--scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      baxis--color:            ['Axis',         'color',    '#aabb99']
      baxis--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      baxis--linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]

  octahedron:

    title:               Octahedron
    controls:
      ewireframe--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      ewireframe--color:       ['Wireframe',    'color',    '#ff00ff']
      ewireframe--opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      ewireframe--linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      evertexid--label:        ['IDs',          'label']
      evertexid--opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      evertexids--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      eface--color:            ['Faces',        'color',    '#88cccc']
      eface--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      efaceid--label:          ['IDs',          'label']
      efaceid--opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      efaceids--scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      eaxis--color:            ['Axis',         'color',    '#ffbbcc']
      eaxis--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      eaxis--linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]

  tetrahedron:

    title:               Tetrahedron
    controls:
      dwireframe--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      dwireframe--color:       ['Wireframe',    'color',    '#ff00ff']
      dwireframe--opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      dwireframe--linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      dvertexid--label:        ['IDs',          'label']
      dvertexid--opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      dvertexids--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      dface--color:            ['Faces',        'color',    '#88cccc']
      dface--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      dfaceid--label:          ['IDs',          'label']
      dfaceid--opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      dfaceids--scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      daxis--color:            ['Axis',         'color',    '#ffbbcc']
      daxis--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      daxis--linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]

  cube:

    title:               Cube
    controls:
      cwireframe--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      cwireframe--color:       ['Wireframe',    'color',    '#ff00ff']
      cwireframe--opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      cwireframe--linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      cvertexid--label:        ['IDs',          'label']
      cvertexid--opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      cvertexids--scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      cface--color:            ['Faces',        'color',    '#88cccc']
      cface--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      cfaceid--label:          ['IDs',          'label']
      cfaceid--opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      cfaceids--scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      caxis--color:            ['Axis',         'color',    '#ffbbcc']
      caxis--opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      caxis--linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]

  scene:
    title:               Scene
    controls:
      header--camera:          ['Camera',        'header']
      camera--perspective:     ['Perspective',   'range',    25, [1, 90, 1]]
      camera--position:        ['Position',      'position', [0, 2000, -2000], [-3000, 3000, 1]]

      hr1:                     [ null, 'hr']
      renderer--color:         ['Background',    'color',    '#fcf3ff']

      hr2:                     [ null, 'hr']
      plane--color:            ['Plane',         'color',    '#cccccc']
      plane--opacity:          ['Opacity',       'range',    1, [0, 1, .01]]
      plane--width:            ['Width',         'range',    850, [500, 1500, 1]]
      plane--depth:            ['Depth',         'range',    850, [500, 1500, 1]]
      plane--position:         ['Position',      'position', [0, -200, 0], [-1000, 1000, 1]]
      plane--rotation:         ['Rotation',      'rotation', [0, -180, 1], [-180, 180, 1]]
  lighting:
    title:               Lighting
    controls:
      ambient--color:          ['Ambient',       'color',    '#777777']
      hr1:                     [ null, 'hr']
      spotlight-1--color:      ['Spotlight 1',   'color',    '#664466']
      spotlight-1--position:   ['Position',      'position', [-500, 800, -500], [-1000, 1000, 1]]
      hr2:                     [ null, 'hr']
      spotlight-2--color:      ['Spotlight 2',   'color',    '#446644']
      spotlight-2--position:   ['Position',      'position', [ 800, 800, -200], [-1000, 1000, 1]]
      hr3:                     [ null, 'hr']
      spotlight-3--color:      ['Spotlight 3',   'color',    '#000000']
      spotlight-3--position:   ['Position',      'position', [-500, 800, -500], [-1000, 1000, 1]]
  mouse:
    title: Mouse
    controls:
      mouse--mode:
        - Mouse mode
        - radios
        - camera
        -
          camera:      Move Camera
          attach:      Attach Nuclets
          atom:        Move Atom
          spotlight-1: Move Spotlight 1
          spotlight-2: Move Spotlight 2
          spotlight-3: Move Spotlight 3
          none:        None

