name: Atom Builder
mouse:
styler:
  style:
    title:               Styles
    controls:
      style__reset:            ['Reset Style',      'button']
      hr1:                     [ null,              'hr']
      style__loadlabel:        ['Current Style',    'header']
      style__selectyml:        [ null,              'selectyml', 'base.yml',   'style',   'config/style/builder', 'atomizer.ajax_yml_load']
      hr2:                     [ null,              'hr']
      style__savelabel:        ['Create New Style', 'header']
      style__saveyml:          [ null,              'saveyml',   '',           'style',   'config/style/builder', 'atomizer.ajax_yml_save']

  proton:
    title:               Protons
    controls:
      proton_default__color:   ['Default',      'color',    '#6666dd']
      proton_top__color:       ['Top',          'color',    '#d4af37']
      proton_bottom__color:    ['Bottom',       'color',    '#dd66dd']
      proton_marker__color:    ['Marker',       'color',    '#55dddd']
      proton__opacity:         ['Opacity',      'range',    .9, [0, 1, .01]]
      proton__scale:           ['Scale',        'range',     1, [0, 2, .01]]

  isocahedron:

    title:               Isocahedron
    controls:

      awireframe__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      awireframe__color:       ['Wireframe',    'color',    '#aaffcc']
      awireframe__opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      awireframe__linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      avertexid__label:        ['IDs',          'label']
      avertexid__opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      avertexids__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      aface__color:            ['Faces',        'color',    '#88cccc']
      aface__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      afaceid__label:          ['IDs',          'label']
      afaceid__opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      afaceids__scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      aaxis__color:            ['Axis',         'color',    '#ffbbcc']
      aaxis__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      aaxis__linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]


  dodecahedron:

    title:               Dodecahedron
    controls:
      bwireframe__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      bwireframe__color:       ['Wireframe',    'color',    '#ffdd33']
      bwireframe__opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      bwireframe__linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      bvertexid__label:        ['IDs',          'label']
      bvertexid__opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      bvertexids__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      bface__color:            ['Faces',        'color',    '#88cccc']
      bface__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      bfaceid__label:          ['IDs',          'label']
      bfaceid__opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      bfaceids__scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      baxis__color:            ['Axis',         'color',    '#aabb99']
      baxis__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      baxis__linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]

  octahedron:

    title:               Octahedron
    controls:
      ewireframe__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      ewireframe__color:       ['Wireframe',    'color',    '#ff00ff']
      ewireframe__opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      ewireframe__linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      evertexid__label:        ['IDs',          'label']
      evertexid__opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      evertexids__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      eface__color:            ['Faces',        'color',    '#88cccc']
      eface__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      efaceid__label:          ['IDs',          'label']
      efaceid__opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      efaceids__scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      eaxis__color:            ['Axis',         'color',    '#ffbbcc']
      eaxis__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      eaxis__linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]

  tetrahedron:

    title:               Tetrahedron
    controls:
      dwireframe__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      dwireframe__color:       ['Wireframe',    'color',    '#ff00ff']
      dwireframe__opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      dwireframe__linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      dvertexid__label:        ['IDs',          'label']
      dvertexid__opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      dvertexids__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      dface__color:            ['Faces',        'color',    '#88cccc']
      dface__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      dfaceid__label:          ['IDs',          'label']
      dfaceid__opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      dfaceids__scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      daxis__color:            ['Axis',         'color',    '#ffbbcc']
      daxis__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      daxis__linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]

  cube:

    title:               Cube
    controls:
      cwireframe__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr1:                     [ null, 'hr']
      cwireframe__color:       ['Wireframe',    'color',    '#ff00ff']
      cwireframe__opacity:     ['Opacity',      'range',    .3, [0, 1, .01]]
      cwireframe__linewidth:   ['Linewidth',    'range',     1, [0, 5, .1]]

      cvertexid__label:        ['IDs',          'label']
      cvertexid__opacity:      ['Opacity',      'range',    .3, [0, 1, .01]]
      cvertexids__scale:       ['Scale',        'range',    1,  [0, 2, .01]]

      hr2:                     [ null, 'hr']
      cface__color:            ['Faces',        'color',    '#88cccc']
      cface__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]

      cfaceid__label:          ['IDs',          'label']
      cfaceid__opacity:        ['Opacity',      'range',    .3, [0, 1, .01]]
      cfaceids__scale:         ['Scale',        'range',    1,  [0, 2, .01]]

      hr4:                     [ null, 'hr']
      caxis__color:            ['Axis',         'color',    '#ffbbcc']
      caxis__opacity:          ['Opacity',      'range',     0, [0, 1, .01]]
      caxis__linewidth:        ['Linewidth',    'range',     1, [0, 5, .1]]

  scene:
    title:               Scene
    controls:
      header__camera:          ['Camera',        'header']
      camera__perspective:     ['Perspective',   'range',    25, [1, 90, 1]]
      camera__position:        ['Position',      'position', [0, 2000, -2000], [-3000, 3000, 1]]

      hr1:                     [ null, 'hr']
      renderer__color:         ['Background',    'color',    '#fcf3ff']

      hr2:                     [ null, 'hr']
      plane__color:            ['Plane',         'color',    '#cccccc']
      plane__opacity:          ['Opacity',       'range',    1, [0, 1, .01]]
      plane__width:            ['Width',         'range',    850, [500, 1500, 1]]
      plane__depth:            ['Depth',         'range',    850, [500, 1500, 1]]
      plane__position:         ['Position',      'position', [0, -200, 0], [-1000, 1000, 1]]
      plane__rotation:         ['Rotation',      'rotation', [0, -180, 1], [-180, 180, 1]]
  lighting:
    title:               Lighting
    controls:
      ambient__color:          ['Ambient',       'color',    '#777777']
      hr1:                     [ null, 'hr']
      spotlight_1__color:      ['Spotlight 1',   'color',    '#664466']
      spotlight_1__position:   ['Position',      'position', [-500, 800, -500], [-1000, 1000, 1]]
      hr2:                     [ null, 'hr']
      spotlight_2__color:      ['Spotlight 2',   'color',    '#446644']
      spotlight_2__position:   ['Position',      'position', [ 800, 800, -200], [-1000, 1000, 1]]
      hr3:                     [ null, 'hr']
      spotlight_3__color:      ['Spotlight 3',   'color',    '#000000']
      spotlight_3__position:   ['Position',      'position', [-500, 800, -500], [-1000, 1000, 1]]
  mouse:
    title: Mouse
    controls:
      mouse__mode:
        - Mouse mode
        - radios
        - camera
        -
          camera:      Move Camera
          attach:      Attach Nuclets
          atom:        Move Atom
          spotlight_1: Move Spotlight 1
          spotlight_2: Move Spotlight 2
          spotlight_3: Move Spotlight 3
          none:        None

