name: Base
description: 'Initial style set'
filepath: config/style/atom_builder/base.yml
styles:
  ambient--color:
    defaultValue: '#5e5e5e'
    type: color
  attachLines--linewidth:
    defaultValue: 1
    type: range
  attachLines--opacity:
    defaultValue: 0
    type: range
  attachLines--scale:
    defaultValue: 3
    type: range
  camera--perspective:
    defaultValue: 25
    type: range
  camera--position--x:
    defaultValue: 0
    type: position
  camera--position--y:
    defaultValue: 700
    type: position
  camera--position--z:
    defaultValue: -1500
    type: position
  deca--scale:
    defaultValue: 1
    type: range
  decaAxes--color:
    defaultValue: '#aabb99'
    type: color
  decaAxes--linewidth:
    defaultValue: 1
    type: range
  decaAxes--opacity:
    defaultValue: 0
    type: range
  decaAxes--scale:
    defaultValue: 2
    type: range
  decaFaceid--opacity:
    defaultValue: 0
    type: range
  decaFaceids--scale:
    defaultValue: 1
    type: range
  decaFaces--color:
    defaultValue: '#88cccc'
    type: color
  decaFaces--opacity:
    defaultValue: 0
    type: range
  decaVertexid--opacity:
    defaultValue: 0
    type: range
  decaVertexids--scale:
    defaultValue: 1
    type: range
  decaWireframe--color:
    defaultValue: '#00ff15'
    type: color
  decaWireframe--linewidth:
    defaultValue: '1'
    type: range
  decaWireframe--opacity:
    defaultValue: 1
    type: range
  decahedron--position--x:
    defaultValue: 0
    type: position
  decahedron--position--y:
    defaultValue: 0
    type: position
  decahedron--position--z:
    defaultValue: 0
    type: position
  decahedron--rotation--x:
    defaultValue: 0
    type: rotation
  decahedron--rotation--y:
    defaultValue: 0
    type: rotation
  decahedron--rotation--z:
    defaultValue: 0
    type: rotation
  dodeca--scale:
    defaultValue: 1
    type: range
  dodecaAxes--color:
    defaultValue: '#aabb99'
    type: color
  dodecaAxes--linewidth:
    defaultValue: 1
    type: range
  dodecaAxes--opacity:
    defaultValue: 0
    type: range
  dodecaAxes--scale:
    defaultValue: 2
    type: range
  dodecaAxis--color:
    defaultValue: '#aabb99'
    type: color
  dodecaAxis--linewidth:
    defaultValue: 1
    type: range
  dodecaAxis--opacity:
    defaultValue: 0
    type: range
  dodecaFaceid--opacity:
    defaultValue: 0
    type: range
  dodecaFaceids--scale:
    defaultValue: 1
    type: range
  dodecaFaces--color:
    defaultValue: '#000000'
    type: color
  dodecaFaces--opacity:
    defaultValue: '0.35'
    type: range
  dodecaVertexid--opacity:
    defaultValue: 0
    type: range
  dodecaVertexids--scale:
    defaultValue: 1
    type: range
  dodecaWireframe--color:
    defaultValue: '#00d5ff'
    type: color
  dodecaWireframe--linewidth:
    defaultValue: '0.5'
    type: range
  dodecaWireframe--opacity:
    defaultValue: 1
    type: range
  dodecaWireframe--scale:
    defaultValue: 1
    type: range
  electron--color:
    defaultValue: '#ffff33'
    type: color
  electron--opacity:
    defaultValue: 1
    type: range
  electron--radius:
    type: range
    defaultValue: 5
  electron--scale:
    defaultValue: '0.59'
    type: range
  hexaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  hexaAxes--linewidth:
    defaultValue: 1
    type: range
  hexaAxes--opacity:
    defaultValue: 0
    type: range
  hexaAxes--scale:
    defaultValue: 2
    type: range
  hexaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  hexaAxis--linewidth:
    defaultValue: 1
    type: range
  hexaAxis--opacity:
    defaultValue: 0
    type: range
  hexaFace--color:
    defaultValue: '#88cccc'
    type: color
  hexaFace--opacity:
    defaultValue: 0
    type: range
  hexaFaceid--opacity:
    defaultValue: 0
    type: range
  hexaFaceids--scale:
    defaultValue: 1
    type: range
  hexaVertexid--opacity:
    defaultValue: 0
    type: range
  hexaVertexids--scale:
    defaultValue: 1
    type: range
  hexaWcireframe--color:
    defaultValue: '#55ff55'
    type: color
  hexaWcireframe--linewidth:
    defaultValue: 1
    type: range
  hexaWcireframe--opacity:
    defaultValue: 1
    type: range
  hexaWireframe--color:
    defaultValue: '#55ff55'
    type: color
  hexaWireframe--linewidth:
    defaultValue: 1
    type: range
  hexaWireframe--opacity:
    defaultValue: 1
    type: range
  hexaWireframe--scale:
    defaultValue: 1
    type: range
  icosa--scale:
    defaultValue: 1
    type: range
  icosaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaAxes--linewidth:
    defaultValue: 1
    type: range
  icosaAxes--opacity:
    defaultValue: 0
    type: range
  icosaAxes--scale:
    defaultValue: 2
    type: range
  icosaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaAxis--linewidth:
    defaultValue: 1
    type: range
  icosaAxis--opacity:
    defaultValue: 0
    type: range
  icosaFaceid--opacity:
    defaultValue: 0
    type: range
  icosaFaceids--scale:
    defaultValue: 1
    type: range
  icosaFaces--color:
    defaultValue: '#88cccc'
    type: color
  icosaFaces--opacity:
    defaultValue: 0
    type: range
  icosaVertexid--opacity:
    defaultValue: 0
    type: range
  icosaVertexids--scale:
    defaultValue: 1
    type: range
  icosaWireframe--color:
    defaultValue: '#ff0000'
    type: color
  icosaWireframe--linewidth:
    defaultValue: '0.5'
    type: range
  icosaWireframe--opacity:
    defaultValue: 1
    type: range
  icosaWireframe--scale:
    defaultValue: 1
    type: range
  nuclet--attachAngle:
    defaultValue: '5'
    type: range
  nucletAxes--linewidth:
    defaultValue: 1
    type: range
  nucletAxes--opacity:
    defaultValue: 0
    type: range
  nucletAxes--scale:
    defaultValue: 4
    type: range
  nucletInnerAxes--linewidth:
    defaultValue: 3
    type: range
  nucletInnerAxes--opacity:
    defaultValue: 0
    type: range
  nucletInnerAxes--scale:
    defaultValue: 3
    type: range
  nucletOuterAxes--linewidth:
    defaultValue: 5
    type: range
  nucletOuterAxes--opacity:
    defaultValue: 0
    type: range
  nucletOuterAxes--scale:
    defaultValue: 2
    type: range
  octa--rotation--x:
    defaultValue: 0
    type: rotation
  octa--rotation--y:
    defaultValue: 0
    type: rotation
  octa--rotation--z:
    defaultValue: 1
    type: rotation
  octa--scale:
    defaultValue: '1.02'
    type: range
  octaAexis--linewidth:
    defaultValue: 1
    type: range
  octaAexis--opacity:
    defaultValue: 0
    type: range
  octaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  octaAxes--linewidth:
    defaultValue: 1
    type: range
  octaAxes--opacity:
    defaultValue: 0
    type: range
  octaAxes--scale:
    defaultValue: 2
    type: range
  octaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  octaVertexid--opacity:
    defaultValue: 0
    type: range
  octaVertexids--scale:
    defaultValue: 1
    type: range
  octaWireframe--color:
    defaultValue: '#ffff00'
    type: color
  octaWireframe--linewidth:
    defaultValue: '0.5'
    type: range
  octaWireframe--opacity:
    defaultValue: 1
    type: range
  octaWireframe--scale:
    defaultValue: 1
    type: range
  plane--color:
    defaultValue: '#878787'
    type: color
  plane--depth:
    defaultValue: 1200
    type: range
  plane--opacity:
    defaultValue: 1
    type: range
  plane--position--x:
    defaultValue: 0
    type: position
  plane--position--y:
    defaultValue: -200
    type: position
  plane--position--z:
    defaultValue: 0
    type: position
  plane--rotation--x:
    defaultValue: 0
    type: rotation
  plane--rotation--y:
    defaultValue: -180
    type: rotation
  plane--rotation--z:
    defaultValue: 1
    type: rotation
  plane--width:
    defaultValue: 1500
    type: range
  proton--opacity:
    defaultValue: '0.42'
    type: range
  proton--radius:
    type: range
    defaultValue: 50
  proton--scale:
    defaultValue: 1
    type: range
  proton-default--color:
    defaultValue: '#767676'
    type: color
  proton-ghost--color:
    defaultValue: '#ac58ac'
    type: color
  proton-grow--color:
    defaultValue: '#3d5744'
    type: color
  proton-neutral--color:
    defaultValue: '#584961'
    type: color
  proton-polar--color:
    defaultValue: '#454b5b'
    type: color
  proton-valence--color:
    defaultValue: '#534444'
    type: color
  protonVertexid--color:
    defaultValue: '#fc78fc'
    type: color
  protonVertexid--opacity:
    defaultValue: 0
    type: range
  protonVertexid--scale:
    defaultValue: 1
    type: range
  protons--scale:
    defaultValue: 1
    type: range
  renderer--color:
    defaultValue: '#95acbc'
    type: color
  spotlight-1--color:
    defaultValue: '#9c789c'
    type: color
  spotlight-1--position--x:
    defaultValue: -500
    type: position
  spotlight-1--position--y:
    defaultValue: 800
    type: position
  spotlight-1--position--z:
    defaultValue: -500
    type: position
  spotlight-2--color:
    defaultValue: '#8eb6b6'
    type: color
  spotlight-2--position--x:
    defaultValue: 800
    type: position
  spotlight-2--position--y:
    defaultValue: 800
    type: position
  spotlight-2--position--z:
    defaultValue: -200
    type: position
  spotlight-3--color:
    defaultValue: '#b0b089'
    type: color
  spotlight-3--position--x:
    defaultValue: -500
    type: position
  spotlight-3--position--y:
    defaultValue: 800
    type: position
  spotlight-3--position--z:
    defaultValue: -500
    type: position
  tetraAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  tetraAxes--linewidth:
    defaultValue: 1
    type: range
  tetraAxes--opacity:
    defaultValue: 0
    type: range
  tetraAxes--scale:
    defaultValue: 2
    type: range
  tetraAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  tetraAxis--linewidth:
    defaultValue: 1
    type: range
  tetraAxis--opacity:
    defaultValue: 0
    type: range
  tetraFaceid--opacity:
    defaultValue: 0
    type: range
  tetraFaceids--scale:
    defaultValue: '1.33'
    type: range
  tetraFaces--color:
    defaultValue: '#00fcff'
    type: color
  tetraFaces--opacity:
    defaultValue: '0'
    type: range
  tetraVertexid--opacity:
    defaultValue: 0
    type: range
  tetraVertexids--scale:
    defaultValue: 1
    type: range
  tetraWireframe--color:
    defaultValue: '#0034ff'
    type: color
  tetraWireframe--linewidth:
    defaultValue: '0.5'
    type: range
  tetraWireframe--opacity:
    defaultValue: '1'
    type: range
  tetraWireframe--scale:
    defaultValue: 1
    type: range
  valence--diameter:
    defaultValue: 0.12
    type: range
  valence--opacity:
    defaultValue: '1'
    type: range
  valence--scale:
    defaultValue: '1'
    type: range
  valence-active--color:
    defaultValue: '#85223C'
    type: color
  valence-inactive--color:
    defaultValue: '#666666'
    type: color
