name: Atom Viewer
defaultView: viewer
styleSetDirectory: config/style/atom_viewer
libraries: [atomizer/atomizer-base, atomizer/atomizer-atom-viewer]
objects: [nuclets]
canvasRatio: window
views:
  viewer:
    name: Atom Viewer
    producer: atom_viewer
    defaultAtom: carbon.yml
    styleSetPath: config/style/atom_viewer/base.yml
