name: Platonic Solids
defaultView: solids
themeDirectory: config/themes/platonic_solids
animateDirectory: config/animations/platonic_solids
controlFile: controls_platonic_solids.yml
atomizerId: platonic-solids
classes: [az-overlay-controls]
objects: [solids]
canvasRatio: .50
libraries: [atomizer/atomizer-base, atomizer/atomizer-platonic-solids]
views:
  solids:
    name: Platonic solids
    producer: platonic_solids
    defaultTheme: Default.yml

