name:  Backbone
defaultView: backbone
styleSetDirectory: config/style/backbone
views:
  backbone:
    name: Backbone Builder
    producer: backbone_builder
    defaultAtom: half_backbone.yml
    styleSetPath: config/style/builder/backbone.yml
