name: Element Viewer
defaultView: fivesolids
controlSet: control/element.yml
views:
  fiveSolids:
    name: The 5 Platonic Solids
    producer: platonic_solids
    defaultTheme: Default.yml
  dualSolids:
    name: Platonic solids and their duals 
    producer: platonic_solids_dual
    defaultTheme: Default.yml
  octoNiso:
    name: The Octahedron and IsocaHedron
    producer: octo_and_iso_solids
    defaultTheme: Default.yml
