name: Build Atoms
animations:
  rotation:
    name: orbitals
    speed: .07
timers:
# opacity-protons:
#   name: protons
#   time: 5000
#   duration: 1000
  loadatoms:
    time: 3000
    atoms:
      - {name: hydrogen-1, nid: 89, time: 3000}
      - {name: hydrogen-2, nid: 87}
      - {name: hydrogen-3, nid: 88}
      - {name: helium-4, nid: 86, time: 5000}
      - {name: lithium-6, nid: 90}
      - {name: lithium-7, nid: 91}
      - {name: beryllium-9, nid: 84}
      - {name: boron-11, nid: 100}
      - {name: carbon-12, nid: 73, time: 10000}
      - {name: nitrogen-14, nid: 267}
      - {name: oxygen-16, nid: 93}
      - {name: flourine-19, nid: 85}
      - {name: neon-20, nid: 94}
      - {name: sodium-natrium, nid: 240}
      - {name: magnesium-24, nid: 81}
      - {name: almost-aluminum, nid: 230}
      - {name: silicon, nid: 233, time: 15000}
      - {name: phosophorous, nid: 235}
      - {name: chlorine, nid: 231}
      - {name: argon-38, nid: 236}
      - {name: potassium, nid: 234}
      - {name: calcium-40, nid: 237}
      - {name: scandium, nid: 239}
      - {name: titanium-46, nid: 238}
      - {name: vanadium-51, nid: 242}
      - {name: chromium-52, nid: 243}
      - {name: manganese-55, nid: 244}
      - {name: iron-56-1-active-nuclet-ending, nid: 273}

