name: Base
description: 'Initial style set'
styles:
  proton--radius:
    type: range
    defaultValue: 50
  electron--radius:
    type: range
    defaultValue: 5
  nucleus--position--x:
    defaultValue:
      - 0
      - 0
      - 0
    type: position
  nucleus--position--y:
    defaultValue:
      - 0
      - 0
      - 0
    type: position
  nucleus--position--z:
    defaultValue:
      - 0
      - 0
      - 0
    type: position
  nucleus--rotation--x:
    defaultValue:
      - 0
      - 0
      - 0
    type: rotation
  nucleus--rotation--y:
    defaultValue:
      - 0
      - 0
      - 0
    type: rotation
  nucleus--rotation--z:
    defaultValue:
      - 0
      - 0
      - 0
    type: rotation
  proton-default--color:
    defaultValue: '#767676'
    type: color
  proton--opacity:
    defaultValue: '1'
    type: range
  proton--scale:
    defaultValue: '1'
    type: range
  icosaWireframe--scale:
    defaultValue: 1
    type: range
  icosaWireframe--color:
    defaultValue: '#ffbb33'
    type: color
  icosaWireframe--opacity:
    defaultValue: '1'
    type: range
  icosaWireframe--linewidth:
    defaultValue: '2.2'
    type: range
  icosaVertexid--opacity:
    defaultValue: 0
    type: range
  icosaVertexids--scale:
    defaultValue: 1
    type: range
  icosaFaces--color:
    defaultValue: '#88cccc'
    type: color
  icosaFaces--opacity:
    defaultValue: 0
    type: range
  icosaFaceid--opacity:
    defaultValue: 0
    type: range
  icosaFaceids--scale:
    defaultValue: 1
    type: range
  icosaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaAxis--opacity:
    defaultValue: 0
    type: range
  icosaAxis--linewidth:
    defaultValue: 1
    type: range
  dodecaWireframe--scale:
    defaultValue: 1
    type: range
  dodecaWireframe--color:
    defaultValue: '#00d5ff'
    type: color
  dodecaWireframe--opacity:
    defaultValue: 1
    type: range
  dodecaWireframe--linewidth:
    defaultValue: '2.3'
    type: range
  dodecaVertexid--opacity:
    defaultValue: 0
    type: range
  dodecaVertexids--scale:
    defaultValue: 1
    type: range
  dodecaFaces--color:
    defaultValue: '#000000'
    type: color
  dodecaFaces--opacity:
    defaultValue: '0.61'
    type: range
  dodecaFaceid--opacity:
    defaultValue: '0'
    type: range
  dodecaFaceids--scale:
    defaultValue: 1
    type: range
  dodecaAxis--color:
    defaultValue: '#aabb99'
    type: color
  dodecaAxis--opacity:
    defaultValue: 0
    type: range
  dodecaAxis--linewidth:
    defaultValue: 1
    type: range
  octaWireframe--scale:
    defaultValue: 1
    type: range
  octaWireframe--color:
    defaultValue: '#ffff33'
    type: color
  octaWireframe--opacity:
    defaultValue: 1
    type: range
  octaWireframe--linewidth:
    defaultValue: '2'
    type: range
  octaVertexid--opacity:
    defaultValue: '0'
    type: range
  octaVertexids--scale:
    defaultValue: 1
    type: range
  octaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  octaAexis--opacity:
    defaultValue: 0
    type: range
  octaAexis--linewidth:
    defaultValue: 1
    type: range
  tetraWireframe--scale:
    defaultValue: '1.02'
    type: range
  tetraWireframe--color:
    defaultValue: '#c73eff'
    type: color
  tetraWireframe--opacity:
    defaultValue: '1'
    type: range
  tetraWireframe--linewidth:
    defaultValue: '2.6'
    type: range
  tetraVertexid--opacity:
    defaultValue: '0'
    type: range
  tetraVertexids--scale:
    defaultValue: 1
    type: range
  tetraAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  tetraAxis--opacity:
    defaultValue: 0
    type: range
  tetraAxis--linewidth:
    defaultValue: 1
    type: range
  hexaWireframe--scale:
    defaultValue: 1
    type: range
  hexaWcireframe--color:
    defaultValue: '#55ff55'
    type: color
  hexaWcireframe--opacity:
    defaultValue: 1
    type: range
  hexaWcireframe--linewidth:
    defaultValue: 1
    type: range
  hexaVertexid--opacity:
    defaultValue: 0
    type: range
  hexaVertexids--scale:
    defaultValue: 1
    type: range
  hexaFace--color:
    defaultValue: '#88cccc'
    type: color
  hexaFace--opacity:
    defaultValue: 0
    type: range
  hexaFaceid--opacity:
    defaultValue: 0
    type: range
  hexaFaceids--scale:
    defaultValue: 1
    type: range
  hexaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  hexaAxis--opacity:
    defaultValue: 0
    type: range
  hexaAxis--linewidth:
    defaultValue: 1
    type: range
  valence--color:
    defaultValue: '#ff00ff'
    type: color
  valence--opacity:
    defaultValue: 0.3
    type: range
  isotope--color:
    defaultValue: '#0000ff'
    type: color
  isotope--opacity:
    defaultValue: 0.3
    type: range
  camera--perspective:
    defaultValue: 25
    type: range
  camera--position--x:
    defaultValue:
      - 0
      - 500
      - -1600
    type: position
  camera--position--y:
    defaultValue:
      - 0
      - 500
      - -1600
    type: position
  camera--position--z:
    defaultValue:
      - 0
      - 500
      - -1600
    type: position
  renderer--color:
    defaultValue: '#778d97'
    type: color
  plane--color:
    defaultValue: '#6a6a6a'
    type: color
  plane--opacity:
    defaultValue: 1
    type: range
  plane--width:
    defaultValue: 1500
    type: range
  plane--depth:
    defaultValue: 1200
    type: range
  plane--position--x:
    defaultValue:
      - 0
      - -200
      - 0
    type: position
  plane--position--y:
    defaultValue:
      - 0
      - -200
      - 0
    type: position
  plane--position--z:
    defaultValue:
      - 0
      - -200
      - 0
    type: position
  plane--rotation--x:
    defaultValue:
      - 0
      - -180
      - 1
    type: rotation
  plane--rotation--y:
    defaultValue:
      - 0
      - -180
      - 1
    type: rotation
  plane--rotation--z:
    defaultValue:
      - 0
      - -180
      - 1
    type: rotation
  ambient--color:
    defaultValue: '#888888'
    type: color
  spotlight-1--color:
    defaultValue: '#775577'
    type: color
  spotlight-1--position--x:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-1--position--y:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-1--position--z:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-2--color:
    defaultValue: '#557777'
    type: color
  spotlight-2--position--x:
    defaultValue:
      - 800
      - 800
      - -200
    type: position
  spotlight-2--position--y:
    defaultValue:
      - 800
      - 800
      - -200
    type: position
  spotlight-2--position--z:
    defaultValue:
      - 800
      - 800
      - -200
    type: position
  spotlight-3--color:
    defaultValue: '#777755'
    type: color
  spotlight-3--position--x:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-3--position--y:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-3--position--z:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  electron--color:
    defaultValue: '#ffff33'
    type: color
  electron--opacity:
    defaultValue: 1
    type: range
  electron--scale:
    defaultValue: '1'
    type: range
  icosa--scale:
    defaultValue: '1.19'
    type: range
  dodeca--scale:
    defaultValue: '0.83'
    type: range
  octa--scale:
    defaultValue: '0.8'
    type: range
  octa--rotation--x:
    defaultValue: '0'
    type: rotation
  octa--rotation--y:
    defaultValue: 0
    type: rotation
  octa--rotation--z:
    defaultValue: 1
    type: rotation
  hexaWireframe--color:
    defaultValue: '#55ff55'
    type: color
  hexaWireframe--opacity:
    defaultValue: 1
    type: range
  hexaWireframe--linewidth:
    defaultValue: 1
    type: range
  icosaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaAxes--opacity:
    defaultValue: 0
    type: range
  icosaAxes--scale:
    defaultValue: 2
    type: range
  icosaAxes--linewidth:
    defaultValue: 1
    type: range
  dodecaAxes--color:
    defaultValue: '#aabb99'
    type: color
  dodecaAxes--opacity:
    defaultValue: 0
    type: range
  dodecaAxes--scale:
    defaultValue: 2
    type: range
  dodecaAxes--linewidth:
    defaultValue: 1
    type: range
  octaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  octaAxes--opacity:
    defaultValue: 0
    type: range
  octaAxes--scale:
    defaultValue: 2
    type: range
  octaAxes--linewidth:
    defaultValue: 1
    type: range
  tetraAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  tetraAxes--opacity:
    defaultValue: 0
    type: range
  tetraAxes--scale:
    defaultValue: 2
    type: range
  tetraAxes--linewidth:
    defaultValue: 1
    type: range
  hexaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  hexaAxes--opacity:
    defaultValue: 0
    type: range
  hexaAxes--scale:
    defaultValue: 2
    type: range
  hexaAxes--linewidth:
    defaultValue: 1
    type: range
  tetraFaces--color:
    defaultValue: '#00fcff'
    type: color
  tetraFaces--opacity:
    defaultValue: '.45'
    type: range
  tetraFaceid--opacity:
    defaultValue: 0
    type: range
  tetraFaceids--scale:
    defaultValue: '1.33'
    type: range
  deca--scale:
    defaultValue: 1
    type: range
  decaWireframe--color:
    defaultValue: '#00ff15'
    type: color
  decaWireframe--opacity:
    defaultValue: 1
    type: range
  decaWireframe--linewidth:
    defaultValue: '2'
    type: range
  decaVertexid--opacity:
    defaultValue: 0
    type: range
  decaVertexids--scale:
    defaultValue: 1
    type: range
  decaFaces--color:
    defaultValue: '#88cccc'
    type: color
  decaFaces--opacity:
    defaultValue: '0'
    type: range
  decaFaceid--opacity:
    defaultValue: 0
    type: range
  decaFaceids--scale:
    defaultValue: 1
    type: range
  decaAxes--color:
    defaultValue: '#aabb99'
    type: color
  decaAxes--opacity:
    defaultValue: 0
    type: range
  decaAxes--scale:
    defaultValue: 2
    type: range
  decaAxes--linewidth:
    defaultValue: 1
    type: range
  decahedron--position--x:
    defaultValue: 0
    type: position
  decahedron--position--y:
    defaultValue: 0
    type: position
  decahedron--position--z:
    defaultValue: 0
    type: position
  decahedron--rotation--x:
    defaultValue: 0
    type: rotation
  decahedron--rotation--y:
    defaultValue: 0
    type: rotation
  decahedron--rotation--z:
    defaultValue: 0
    type: rotation
  proton-valence--color:
    defaultValue: '#4e3f43'
    type: color
  proton-grow--color:
    defaultValue: '#546756'
    type: color
  proton-polar--color:
    defaultValue: '#444455'
    type: color
  proton-lithium--color:
    defaultValue: '#7f6491'
    type: color
  proton-newproton--color:
    defaultValue: '#555599'
    type: color
  proton-newneutron--color:
    defaultValue: '#559955'
    type: color
  proton-vattach--color:
    defaultValue: '#4ea44e'
    type: color
  proton-iattach--color:
    defaultValue: '#338585'
    type: color
  proton-ghost--color:
    defaultValue: '#aa55aa'
    type: color
  protonVertexid--color:
    defaultValue: '#fc78fc'
    type: color
  protonVertexid--opacity:
    defaultValue: '0'
    type: range
  protonVertexid--scale:
    defaultValue: 1
    type: range
  nucletAxes--opacity:
    defaultValue: '0'
    type: range
  nucletAxes--scale:
    defaultValue: 4
    type: range
  backbone-2--position--x:
    defaultValue: 0
    type: position
  backbone-2--position--y:
    defaultValue: 0
    type: position
  backbone-2--position--z:
    defaultValue: 0
    type: position
  backbone-2--rotation--x:
    defaultValue: 0
    type: rotation
  backbone-2--rotation--y:
    defaultValue: 0
    type: rotation
  backbone-2--rotation--z:
    defaultValue: 0
    type: rotation
  innerbackbone-2--position--x:
    defaultValue: 0
    type: position
  innerbackbone-2--position--y:
    defaultValue: '12'
    type: position
  innerbackbone-2--position--z:
    defaultValue: 0
    type: position
  innerbackbone-2--rotation--x:
    defaultValue: 0
    type: rotation
  innerbackbone-2--rotation--y:
    defaultValue: '-21'
    type: rotation
  innerbackbone-2--rotation--z:
    defaultValue: 0
    type: rotation
  outerbackbone-2--position--x:
    defaultValue: 0
    type: position
  outerbackbone-2--position--y:
    defaultValue: 0
    type: position
  outerbackbone-2--position--z:
    defaultValue: 0
    type: position
  outerbackbone-2--rotation--x:
    defaultValue: 0
    type: rotation
  outerbackbone-2--rotation--y:
    defaultValue: 0
    type: rotation
  outerbackbone-2--rotation--z:
    defaultValue: 0
    type: rotation
  nucletAxes--linewidth:
    defaultValue: 1
    type: range
  backbone-1--position--x:
    defaultValue: 0
    type: position
  backbone-1--position--y:
    defaultValue: 0
    type: position
  backbone-1--position--z:
    defaultValue: 0
    type: position
  backbone-1--rotation--x:
    defaultValue: 0
    type: rotation
  backbone-1--rotation--y:
    defaultValue: 0
    type: rotation
  backbone-1--rotation--z:
    defaultValue: 0
    type: rotation
  nucletInnerAxes--opacity:
    defaultValue: '0'
    type: range
  nucletInnerAxes--scale:
    defaultValue: 3
    type: range
  nucletInnerAxes--linewidth:
    defaultValue: 3
    type: range
  nucletOuterAxes--opacity:
    defaultValue: '0'
    type: range
  nucletOuterAxes--scale:
    defaultValue: 2
    type: range
  nucletOuterAxes--linewidth:
    defaultValue: 5
    type: range
  outerlithium-1--position--x:
    defaultValue: 0
    type: position
  outerlithium-1--position--y:
    defaultValue: 0
    type: position
  outerlithium-1--position--z:
    defaultValue: 0
    type: position
  outerlithium-1--rotation--x:
    defaultValue: 0
    type: rotation
  outerlithium-1--rotation--y:
    defaultValue: 0
    type: rotation
  outerlithium-1--rotation--z:
    defaultValue: 0
    type: rotation
filepath: config/style/builder/base.yml
