name: aa
protons:
  p0:
    position:
      x: 35.276101447486
      'y': 35.276101447486
      z: 35.276101447486
    attachments:
      - t0
      - t1
      - t3
  p1:
    position:
      x: -35.276101447486
      'y': -35.276101447486
      z: 35.276101447486
    attachments:
      - t0
  p2:
    position:
      x: -35.276101447486
      'y': 35.276101447486
      z: -35.276101447486
    attachments:
      - t0
      - t1
      - t2
      - t3
      - t4
      - t5
      - t12
  p3:
    position:
      x: 35.276101447486
      'y': -35.276101447486
      z: -35.276101447486
    attachments:
      - t0
      - t1
      - t2
      - t13
  p4:
    position:
      x: 58.379734719558
      'y': 58.379734719558
      z: -58.379734719558
    attachments:
      - t1
      - t2
      - t3
      - t4
      - t12
      - t13
      - t14
      - t15
      - t16
  p5:
    position:
      x: 4.072722883688
      'y': 4.072722883688
      z: -120.73997291234
    attachments:
      - t2
      - t12
      - t13
      - t14
  p6:
    position:
      x: 4.072722883688
      'y': 120.73997291234
      z: -4.072722883688
    attachments:
      - t3
      - t4
      - t5
      - t6
      - t7
      - t9
  p7:
    position:
      x: -16.541508008149
      'y': 107.85528050766
      z: -99.962791778101
    attachments:
      - t4
      - t5
      - t6
  p8:
    position:
      x: -90.024666738925
      'y': 117.72169292134
      z: -34.504716579367
    attachments:
      - t5
      - t6
      - t7
      - t8
  p9:
    position:
      x: -33.186077549941
      'y': 195.43582798404
      z: -57.139542017975
    attachments:
      - t6
      - t7
      - t8
      - t9
      - t10
      - t11
  p10:
    position:
      x: -62.899328763678
      'y': 181.40989717071
      z: 36.141120748677
    attachments:
      - t7
      - t8
      - t9
      - t10
  p11:
    position:
      x: -128.1098654856
      'y': 208.98293532011
      z: -32.912658486476
    attachments:
      - t8
  p12:
    position:
      x: 28.646409543796
      'y': 214.01743791471
      z: 17.778446010481
    attachments:
      - t9
      - t10
      - t11
  p13:
    position:
      x: -49.02025929339
      'y': 273.15894300204
      z: 1.9308612486658
    attachments:
      - t10
      - t11
  p14:
    position:
      x: 27.192070700329
      'y': 273.66475947878
      z: -61.095087547545
    attachments:
      - t11
  p15:
    position:
      x: -16.541508008149
      'y': 99.962791778101
      z: -107.85528050766
    attachments:
      - t12
  p16:
    position:
      x: 99.962791778101
      'y': -16.541508008149
      z: -107.85528050766
    attachments:
      - t13
      - t14
      - t15
  p17:
    position:
      x: 73.050533539884
      'y': 65.60289528412
      z: -155.93170856042
    attachments:
      - t14
      - t15
      - t16
      - t17
      - t18
      - t19
  p18:
    position:
      x: 150.17610071057
      'y': 67.549409160519
      z: -94.053844552686
    attachments:
      - t15
      - t16
      - t17
  p19:
    position:
      x: 87.798862792543
      'y': 144.20781617291
      z: -97.750807194936
    attachments:
      - t16
      - t17
      - t18
  p20:
    position:
      x: 148.9624787695
      'y': 126.52990565262
      z: -173.43091470362
    attachments:
      - t17
      - t18
      - t19
      - t20
  p21:
    position:
      x: 56.365689127053
      'y': 156.67716487414
      z: -190.68856001261
    attachments:
      - t18
      - t19
      - t20
      - t21
      - t22
  p22:
    position:
      x: 97.7873069915
      'y': 88.333997169235
      z: -248.94932818896
    attachments:
      - t19
      - t20
      - t21
  p23:
    position:
      x: 129.02625530263
      'y': 182.09057893902
      z: -252.78080403464
    attachments:
      - t20
      - t21
      - t22
  p24:
    position:
      x: 39.823706652634
      'y': 158.20461979465
      z: -288.18151462056
    attachments:
      - t21
      - t22
  p25:
    position:
      x: 52.356478669885
      'y': 242.98087914184
      z: -238.81796912788
    attachments:
      - t22
geometries:
  t0:
    geometry: tetrahedron
    protons:
      - p0
      - p1
      - p2
      - p3
  t1:
    geometry: tetrahedron
    protons:
      - p3
      - p2
      - p0
      - p4
  t2:
    geometry: tetrahedron
    protons:
      - p4
      - p3
      - p2
      - p5
  t3:
    geometry: tetrahedron
    protons:
      - p4
      - p2
      - p0
      - p6
  t4:
    geometry: tetrahedron
    protons:
      - p6
      - p4
      - p2
      - p7
  t5:
    geometry: tetrahedron
    protons:
      - p7
      - p2
      - p6
      - p8
  t6:
    geometry: tetrahedron
    protons:
      - p8
      - p6
      - p7
      - p9
  t7:
    geometry: tetrahedron
    protons:
      - p9
      - p8
      - p6
      - p10
  t8:
    geometry: tetrahedron
    protons:
      - p10
      - p9
      - p8
      - p11
  t9:
    geometry: tetrahedron
    protons:
      - p10
      - p6
      - p9
      - p12
  t10:
    geometry: tetrahedron
    protons:
      - p12
      - p9
      - p10
      - p13
  t11:
    geometry: tetrahedron
    protons:
      - p13
      - p12
      - p9
      - p14
  t12:
    geometry: tetrahedron
    protons:
      - p5
      - p2
      - p4
      - p15
  t13:
    geometry: tetrahedron
    protons:
      - p5
      - p4
      - p3
      - p16
  t14:
    geometry: tetrahedron
    protons:
      - p16
      - p5
      - p4
      - p17
  t15:
    geometry: tetrahedron
    protons:
      - p17
      - p4
      - p16
      - p18
  t16:
    geometry: tetrahedron
    protons:
      - p18
      - p17
      - p4
      - p19
  t17:
    geometry: tetrahedron
    protons:
      - p19
      - p18
      - p17
      - p20
  t18:
    geometry: tetrahedron
    protons:
      - p20
      - p17
      - p19
      - p21
  t19:
    geometry: tetrahedron
    protons:
      - p21
      - p20
      - p17
      - p22
  t20:
    geometry: tetrahedron
    protons:
      - p22
      - p21
      - p20
      - p23
  t21:
    geometry: tetrahedron
    protons:
      - p23
      - p22
      - p21
      - p24
  t22:
    geometry: tetrahedron
    protons:
      - p24
      - p21
      - p23
      - p25
