name: wow
protons:
  p0:
    position:
      x: 35.276101447486
      'y': 35.276101447486
      z: 35.276101447486
    attachments:
      - t0
      - t1
  p1:
    position:
      x: -35.276101447486
      'y': -35.276101447486
      z: 35.276101447486
    attachments:
      - t0
  p2:
    position:
      x: -35.276101447486
      'y': 35.276101447486
      z: -35.276101447486
    attachments:
      - t0
      - t1
      - t2
      - t3
  p3:
    position:
      x: 35.276101447486
      'y': -35.276101447486
      z: -35.276101447486
    attachments:
      - t0
      - t1
      - t2
  p4:
    position:
      x: 58.379734719558
      'y': 58.379734719558
      z: -58.379734719558
    attachments:
      - t1
      - t2
      - t3
      - t4
  p5:
    position:
      x: 4.072722883688
      'y': 4.072722883688
      z: -120.73997291234
    attachments:
      - t2
      - t3
      - t4
      - t5
  p6:
    position:
      x: -16.541508008149
      'y': 99.962791778101
      z: -107.85528050766
    attachments:
      - t3
      - t4
      - t5
      - t6
  p7:
    position:
      x: 65.60289528412
      'y': 73.050533539884
      z: -155.93170856042
    attachments:
      - t4
      - t5
      - t6
      - t7
  p8:
    position:
      x: -22.918713884704
      'y': 59.67051137277
      z: -197.95635931519
    attachments:
      - t5
      - t6
      - t7
      - t8
      - t9
  p9:
    position:
      x: 13.362990911297
      'y': 151.03087381418
      z: -187.09833249503
    attachments:
      - t6
      - t7
      - t8
  p10:
    position:
      x: 53.897697596372
      'y': 89.211687276564
      z: -252.79660823325
    attachments:
      - t7
      - t8
      - t9
      - t10
  p11:
    position:
      x: -36.039833341273
      'y': 126.89016385507
      z: -269.30219555562
    attachments:
      - t8
      - t9
      - t10
  p12:
    position:
      x: -16.736878122024
      'y': 32.817985243484
      z: -292.93839238074
    attachments:
      - t9
      - t10
  p13:
    position:
      x: 23.665862436317
      'y': 106.27592127726
      z: -345.40167219464
    attachments:
      - t10
geometries:
  t0:
    geometry: tetrahedron
    protons:
      - p0
      - p1
      - p2
      - p3
  t1:
    geometry: tetrahedron
    protons:
      - p3
      - p2
      - p0
      - p4
  t2:
    geometry: tetrahedron
    protons:
      - p4
      - p3
      - p2
      - p5
  t3:
    geometry: tetrahedron
    protons:
      - p5
      - p2
      - p4
      - p6
  t4:
    geometry: tetrahedron
    protons:
      - p6
      - p4
      - p5
      - p7
  t5:
    geometry: tetrahedron
    protons:
      - p7
      - p5
      - p6
      - p8
  t6:
    geometry: tetrahedron
    protons:
      - p8
      - p6
      - p7
      - p9
  t7:
    geometry: tetrahedron
    protons:
      - p9
      - p7
      - p8
      - p10
  t8:
    geometry: tetrahedron
    protons:
      - p10
      - p8
      - p9
      - p11
  t9:
    geometry: tetrahedron
    protons:
      - p11
      - p10
      - p8
      - p12
  t10:
    geometry: tetrahedron
    protons:
      - p12
      - p11
      - p10
      - p13
