elements:
  name: Element Viewer
  styleSetDir: stylesets/solids
  controlSet: control/solids.yml
  views:
    fiveSolids:
      name: The 5 Platonic Solids
      function: platonicSolids
      styleSet: base.yml
    dualSolids:
      name: Platonic solids and their duals 
      function: platonicSolidsDuals
      styleSet: base.yml
    octoNiso:
      name: The Octahedron and IsocaHedron
      function: octoAndIsoSolids
      styleSet: base.yml
~                                                                                                               
~                             
