name: Atom Builder
defaultView: builder
themeDirectory: config/themes/atom_builder
libraries: [atomizer/atomizer-base, atomizer/atomizer-atom-builder]
objects: [nuclets]
canvasRatio: window
views:
  builder:
    name: Atom Builder
    producer: atom_builder
    defaultAtom: carbon.yml
    defaultTheme: base.yml
  builder2:
    name: Atom Builder
    producer: atom_builder
    defaultAtom: carbon.yml
    defaultTheme: base.yml

