name: Atom Builder
defaultView: builder
styleSetDirectory: config/style/atom_builder
libraries: [atomizer/atomizer-base, atomizer/atomizer-atom-builder]
objects: [nuclets]
canvasRatio: window
views:
  builder:
    name: Atom Builder
    producer: atom_builder
    defaultAtom: carbon.yml
    styleSetPath: config/style/atom_builder/base.yml
  builder2:
    name: Atom Builder
    producer: atom_builder
    defaultAtom: carbon.yml
    styleSetPath: config/style/atom_builder/base.yml

