name: Atom Viewer
defaultView: viewer
themeDirectory: config/themes/atom_viewer
libraries: [atomizer/atomizer-base, atomizer/atomizer-atom-viewer]
objects: [nuclets]
canvasRatio: .75
views:
  viewer:
    name: Atom Viewer
    producer: atom_viewer
    defaultAtom: carbon.yml
    defaultTheme: base.yml
