name:  Backbone
defaultView: backbone
themeDirectory: config/themes/backbone
views:
  backbone:
    name: Backbone Builder
    producer: backbone_builder
    defaultAtom: half_backbone.yml
    themePath: config/themes/builder/backbone.yml
