name: 04 0 Beryllium 8
element: Beryllium
isotope: 0
variant: 0
numProtons: 8
nuclets:
  1:
    position: 1
    type: carbon
    numProtons: 8
    num_nuclear_electrons: 4
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: false
      5:
        present: false
      6:
        present: true
      7:
        present: true
      8:
        present: true
      9:
        present: false
      10:
        present: false
      11:
        present: true

