name: Beryllium 8
element: Beryllium
isotope: 0
variant: 0
num_protons: 8
nuclets:
  1:
    position: 1
    type: pentalet
    num_protons: 8
    num_nuclear_electrons: 6
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true
      7:
        present: true
      8:
        present: false
      9:
        present: false
      10:
        present: false
      11:
        present: false

