name: 06 -1 Carbon 11
element: Carbon
isotope: 0
variant: 0
numProtons: 12
nuclets:
  N0:
    state: carbon
    numProtons: 12
    numNuclearElectrons: 6
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true
      7:
        present: true
      8:
        present: true
      9:
        present: true
      10:
        present: false
      11:
        present: true3
    electrons:
      0:
        present: true
      1:
        present: true
      2:
        present: false
      3:
        present: true
      4:
        present: true
      5:
        present: true


