name: 06 0 Carbon 12
element: Carbon
isotope: 0
variant: 0
numProtons: 12
nuclets:
  1:
    position: 1
    type: carbon
    numProtons: 12
    numNuclearElectrons: 6
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true
      7:
        present: true
      8:
        present: true
      9:
        present: true
      10:
        present: true
      11:
        present: true
    electrons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true


