name: Carbon 11
name: Carbon 11
element: Carbon
isotope: 0
variant: 0
numProtons: 12
nuclets:
  1:
    position: 1
    type: icosalet
    numProtons: 12
    numNuclearElectrons: 6
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true
      7:
        present: true
      8:
        present: true
      9:
        present: true
      10:
        present: false
      11:
        present: true

