name: Helium
element: Helium
isotope: 0
variant: 0
num_protons: 4
nuclets:
  1:
    position: 1
    type: tetralet
    num_protons: 4
    num_nuclear_electrons: 0
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
