name: 02 0 Helium
element: Helium
isotope: 0
variant: 0
numProtons: 4
nuclets:
  1:
    position: 1
    type: helium
    numProtons: 4
    num_nuclear_electrons: 0
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
