name: 01 0 Hydrogen
element: Hydrogen
isotope: 0
variant: 0
numProtons: 1
nuclets:
  N0:
    state: hydrogen
    numProtons: 1
    num_nuclear_electrons: 0
    protons:
      0:
        present: false
      1:
        present: true
      2:
        present: false
