name: 01 2 Hydrogen Tritium
element: Hydrogen
isotope: 0
variant: 0
numProtons: 3
nuclets:
  1:
    position: 1
    type: hydrogen
    numProtons: 3
    num_nuclear_electrons: 0
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
