name: 01 0 Hydrogen
element: Hydrogen
isotope: 0
variant: 0
num_protons: 1
nuclets:
  1:
    position: 1
    type: monolet
    num_protons: 1
    num_nuclear_electrons: 0
    protons:
      0:
        present: false
      1:
        present: true
      2:
        present: false
