name: 01 1 Hydrogen Deuterium
element: Hydrogen
isotope: 0
variant: 0
numProtons: 2
nuclets:
  1:
    position: 1
    type: hydrogen
    numProtons: 2
    num_nuclear_electrons: 0
    protons:
      0:
        present: true
      1:
        present: true
      1:
        present: false
