name: 03 1 Lithium 7
element: Lithium
isotope: 0
valence: 0
num_protons: 7
nuclets:
  1:
    position: 1
    type: pentalet
    num_protons: 7
    num_nuclear_electrons: 0
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true
