name: 03 0 Lithium 6
element: Lithium
isotope: 0
valence: 0
numProtons: 6
nuclets:
  1:
    position: 1
    type: lithium
    numProtons: 7
    num_nuclear_electrons: 0
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: false
      4:
        present: true
      5:
        present: true
      6:
        present: true
