name: 10 0 Neon
element: Neon
isotope: 0
variant: 0
num_protons: 20
nuclets:
  1:
    position: 1
    type: icosalet
    num_protons: 12
    num_nuclear_electrons: 6
    protons:
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true
      7:
        present: true
      8:
        present: true
      9:
        present: true
      10:
        present: true
      11:
        present: true
      12:
        present: true

