name: 10 0 Neon
element: Neon
isotope: 0
variant: 0
numProtons: 20
nuclets:
  1:
    position: 1
    type: backbone
    numProtons: 20
    num_nuclear_electrons: 10
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true
      7:
        present: true
      8:
        present: true
      9:
        present: true
      10:
        present: true
      11:
        present: true
      12:
        present: true
      13:
        present: true
      14:
        present: true
      15:
        present: true
      16:
        present: true
      17:
        present: true
      18:
        present: true
      19:
        present: true

