name: 07 0 Nitrogen
element: Nitrogen
isotope: 0
variant: 0
numProtons: 14
nuclets:
  1:
    location: 1
    type: carbon
    numProtons: 12
    numNuclearElectrons: 6
    protons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true
      7:
        present: true
      8:
        present: true
      9:
        present: true
      10:
        present: true
      11:
        present: true
    electrons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
  2:
    location: 2
    position:
      x: -80
      y: 80
      z: -140
    rotation:
      x: -45
      y: 0
      z: 20
    type: lithium
    numProtons: 2
    numNuclearElectrons: 7
    protons:
      0:
        present: true
      1:
        present: false
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true
      6:
        present: true

