name: 07 0 Nitrogen
element: Nitrogen
isotope: 0
variant: 0
numProtons: 14
nuclets:
  N0:
    state: backbone-initial
    numProtons: 14
    numInnerElectrons: 6
    protons: [0,1,2,3,4,5,6,7,8,9,10,11,12,13]
    electrons:
      0:
        present: true
      1:
        present: true
      2:
        present: true
      3:
        present: true
      4:
        present: true
      5:
        present: true

