name: Base
description: 'Initial style set'
controls:
  mouse__mode:
    type: radios
    defaultValue: camera
  nucleus__selectyml:
    type: selectyml
    defaultValue: base.yml
  nucleus__saveyml:
    type: saveyml
    defaultValue: base.yml
  style__selectyml:
    type: selectyml
    defaultValue: base.yml
  style__saveyml:
    type: saveyml
    defaultValue: base.yml
  style__reset:
    type: button
    defaultValue: Undefined
  nucleus__position:
    type: position
    defaultValue:
      - 0
      - 0
      - 0
  nucleus__rotation:
    type: rotation
    defaultValue:
      - 0
      - 0
      - 0
  proton__radius:
    type: range
    defaultValue: 50
  proton_default__color:
    type: color
    defaultValue: '#767697'
  proton_top__color:
    type: color
    defaultValue: '#d4af37'
  proton_bottom__color:
    type: color
    defaultValue: '#a569a5'
  proton_marker__color:
    type: color
    defaultValue: '#62baba'
  proton__opacity:
    type: range
    defaultValue: 1
  proton__scale:
    type: range
    defaultValue: 1
  protonid__color:
    type: color
    defaultValue: '#aaddff'
  protonid__opacity:
    type: range
    defaultValue: 1
  protonid__scale:
    type: range
    defaultValue: 1
  nelectrons__color:
    type: color
    defaultValue: '#eeffaa'
  nelectrons__opacity:
    type: range
    defaultValue: 0.3
  nelectrons__scale:
    type: range
    defaultValue: 1
  oelectrons__color:
    type: color
    defaultValue: '#ddbbaa'
  oelectrons__opacity:
    type: range
    defaultValue: 0.3
  oelectrons__scale:
    type: range
    defaultValue: 1
  awireframe__color:
    type: color
    defaultValue: '#0fff14'
  awireframe__opacity:
    type: range
    defaultValue: '1'
  awireframe__scale:
    type: range
    defaultValue: '1.04'
  awireframe__linewidth:
    type: range
    defaultValue: '1'
  avertexid__color:
    type: color
    defaultValue: '#ccaaff'
  avertexid__opacity:
    type: range
    defaultValue: 0.3
  avertexid__scale:
    type: range
    defaultValue: 1
  aface__color:
    type: color
    defaultValue: '#1b1b1b'
  aface__opacity:
    type: range
    defaultValue: '0'
  afaceid__color:
    type: color
    defaultValue: '#aaffee'
  afaceid__opacity:
    type: range
    defaultValue: 0.3
  afaceid__scale:
    type: range
    defaultValue: 1
  aaxis__color:
    type: color
    defaultValue: '#28050e'
  aaxis__opacity:
    type: range
    defaultValue: 0.5
  aaxis__linewidth:
    type: range
    defaultValue: '2.8'
  bwireframe__color:
    type: color
    defaultValue: '#f2ff05'
  bwireframe__opacity:
    type: range
    defaultValue: '1'
  bwireframe__scale:
    type: range
    defaultValue: '1'
  bwireframe__linewidth:
    type: range
    defaultValue: '1'
  bvertexid__color:
    type: color
    defaultValue: '#ffccee'
  bvertexid__opacity:
    type: range
    defaultValue: 0.3
  bvertexid__scale:
    type: range
    defaultValue: '0.5'
  bface__color:
    type: color
    defaultValue: '#235b5b'
  bface__opacity:
    type: range
    defaultValue: '0.29'
  bfaceid__color:
    type: color
    defaultValue: '#ffcc33'
  bfaceid__opacity:
    type: range
    defaultValue: 0.3
  bfaceid__scale:
    type: range
    defaultValue: 1
  baxis__color:
    type: color
    defaultValue: '#aabb99'
  baxis__opacity:
    type: range
    defaultValue: 0.5
  baxis__linewidth:
    type: range
    defaultValue: 1
  valence__color:
    type: color
    defaultValue: '#ff00ff'
  valence__opacity:
    type: range
    defaultValue: 0.3
  isotope__color:
    type: color
    defaultValue: '#0000ff'
  isotope__opacity:
    type: range
    defaultValue: 0.3
  camera__perspective:
    type: range
    defaultValue: 25
  camera__position:
    type: position
    defaultValue:
      - 0
      - 1800
      - -1400
  renderer__color:
    type: color
    defaultValue: '#b7c9b9'
  plane__color:
    type: color
    defaultValue: '#b2a6a6'
  plane__opacity:
    type: range
    defaultValue: 1
  plane__width:
    type: range
    defaultValue: 1000
  plane__depth:
    type: range
    defaultValue: 1000
  plane__position:
    type: position
    defaultValue:
      - 0
      - -250
      - 0
  plane__rotation:
    type: rotation
    defaultValue:
      - 0
      - -180
      - 1
  ambient__color:
    type: color
    defaultValue: '#777777'
  spotlight_1__color:
    type: color
    defaultValue: '#664466'
  spotlight_1__position:
    type: position
    defaultValue:
      - -500
      - 800
      - -500
  spotlight_2__color:
    type: color
    defaultValue: '#446644'
  spotlight_2__position:
    type: position
    defaultValue:
      - 800
      - 800
      - -210
  spotlight_3__color:
    type: color
    defaultValue: '#000000'
  spotlight_3__position:
    type: position
    defaultValue:
      - -500
      - 800
      - -500
filepath: config/style/builder/base.yml
