name: Base
description: 'Initial style set'
styles:
  proton--radius:
    type: range
    defaultValue: 50
  electron--radius:
    type: range
    defaultValue: 5
  nucleus--position--x:
    defaultValue:
      - 0
      - 0
      - 0
    type: position
  nucleus--position--y:
    defaultValue:
      - 0
      - 0
      - 0
    type: position
  nucleus--position--z:
    defaultValue:
      - 0
      - 0
      - 0
    type: position
  nucleus--rotation--x:
    defaultValue:
      - 0
      - 0
      - 0
    type: rotation
  nucleus--rotation--y:
    defaultValue:
      - 0
      - 0
      - 0
    type: rotation
  nucleus--rotation--z:
    defaultValue:
      - 0
      - 0
      - 0
    type: rotation
  proton-default--color:
    defaultValue: '#6666dd'
    type: color
  proton-left--color:
    defaultValue: '#d4af37'
    type: color
  proton-right--color:
    defaultValue: '#dd66dd'
    type: color
  proton-marker--color:
    defaultValue: '#55dddd'
    type: color
  proton--opacity:
    defaultValue: '1'
    type: range
  proton--scale:
    defaultValue: '1'
    type: range
  icosaWireframe--scale:
    defaultValue: 1
    type: range
  icosaWireframe--color:
    defaultValue: '#ff33ff'
    type: color
  icosaWireframe--opacity:
    defaultValue: '1'
    type: range
  icosaWireframe--linewidth:
    defaultValue: '2.2'
    type: range
  icosaVertexid--opacity:
    defaultValue: 0
    type: range
  icosaVertexids--scale:
    defaultValue: 1
    type: range
  icosaFaces--color:
    defaultValue: '#88cccc'
    type: color
  icosaFaces--opacity:
    defaultValue: 0
    type: range
  icosaFaceid--opacity:
    defaultValue: 0
    type: range
  icosaFaceids--scale:
    defaultValue: 1
    type: range
  icosaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaAxis--opacity:
    defaultValue: 0
    type: range
  icosaAxis--linewidth:
    defaultValue: 1
    type: range
  dodecaWireframe--scale:
    defaultValue: 1
    type: range
  dodecaWireframe--color:
    defaultValue: '#00ffff'
    type: color
  dodecaWireframe--opacity:
    defaultValue: 1
    type: range
  dodecaWireframe--linewidth:
    defaultValue: '2.3'
    type: range
  dodecaVertexid--opacity:
    defaultValue: 0
    type: range
  dodecaVertexids--scale:
    defaultValue: 1
    type: range
  dodecaFaces--color:
    defaultValue: '#000000'
    type: color
  dodecaFaces--opacity:
    defaultValue: '0.61'
    type: range
  dodecaFaceid--opacity:
    defaultValue: '0'
    type: range
  dodecaFaceids--scale:
    defaultValue: 1
    type: range
  dodecaAxis--color:
    defaultValue: '#aabb99'
    type: color
  dodecaAxis--opacity:
    defaultValue: 0
    type: range
  dodecaAxis--linewidth:
    defaultValue: 1
    type: range
  octaWireframe--scale:
    defaultValue: 1
    type: range
  octaWireframe--color:
    defaultValue: '#ffff33'
    type: color
  octaWireframe--opacity:
    defaultValue: 1
    type: range
  octaWireframe--linewidth:
    defaultValue: '2'
    type: range
  octaVertexid--opacity:
    defaultValue: '0'
    type: range
  octaVertexids--scale:
    defaultValue: 1
    type: range
  octaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  octaAexis--opacity:
    defaultValue: 0
    type: range
  octaAexis--linewidth:
    defaultValue: 1
    type: range
  tetraWireframe--scale:
    defaultValue: 1
    type: range
  tetraWireframe--color:
    defaultValue: '#ff5555'
    type: color
  tetraWireframe--opacity:
    defaultValue: 0.3
    type: range
  tetraWireframe--linewidth:
    defaultValue: 1
    type: range
  tetraVertexid--opacity:
    defaultValue: 0.3
    type: range
  tetraVertexids--scale:
    defaultValue: 1
    type: range
  tetraAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  tetraAxis--opacity:
    defaultValue: 0
    type: range
  tetraAxis--linewidth:
    defaultValue: 1
    type: range
  hexaWireframe--scale:
    defaultValue: 1
    type: range
  hexaWcireframe--color:
    defaultValue: '#55ff55'
    type: color
  hexaWcireframe--opacity:
    defaultValue: 1
    type: range
  hexaWcireframe--linewidth:
    defaultValue: 1
    type: range
  hexaVertexid--opacity:
    defaultValue: 0
    type: range
  hexaVertexids--scale:
    defaultValue: 1
    type: range
  hexaFace--color:
    defaultValue: '#88cccc'
    type: color
  hexaFace--opacity:
    defaultValue: 0
    type: range
  hexaFaceid--opacity:
    defaultValue: 0
    type: range
  hexaFaceids--scale:
    defaultValue: 1
    type: range
  hexaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  hexaAxis--opacity:
    defaultValue: 0
    type: range
  hexaAxis--linewidth:
    defaultValue: 1
    type: range
  valence--color:
    defaultValue: '#ff00ff'
    type: color
  valence--opacity:
    defaultValue: 0.3
    type: range
  isotope--color:
    defaultValue: '#0000ff'
    type: color
  isotope--opacity:
    defaultValue: 0.3
    type: range
  camera--perspective:
    defaultValue: 25
    type: range
  camera--position--x:
    defaultValue:
      - 0
      - 1000
      - -1000
    type: position
  camera--position--y:
    defaultValue:
      - 0
      - 1000
      - -1000
    type: position
  camera--position--z:
    defaultValue:
      - 0
      - 1000
      - -1000
    type: position
  renderer--color:
    defaultValue: '#fcf3ff'
    type: color
  plane--color:
    defaultValue: '#cccccc'
    type: color
  plane--opacity:
    defaultValue: 1
    type: range
  plane--width:
    defaultValue: 850
    type: range
  plane--depth:
    defaultValue: 850
    type: range
  plane--position--x:
    defaultValue:
      - 0
      - -200
      - 0
    type: position
  plane--position--y:
    defaultValue:
      - 0
      - -200
      - 0
    type: position
  plane--position--z:
    defaultValue:
      - 0
      - -200
      - 0
    type: position
  plane--rotation--x:
    defaultValue:
      - 0
      - -180
      - 1
    type: rotation
  plane--rotation--y:
    defaultValue:
      - 0
      - -180
      - 1
    type: rotation
  plane--rotation--z:
    defaultValue:
      - 0
      - -180
      - 1
    type: rotation
  ambient--color:
    defaultValue: '#777777'
    type: color
  spotlight-1--color:
    defaultValue: '#664466'
    type: color
  spotlight-1--position--x:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-1--position--y:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-1--position--z:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-2--color:
    defaultValue: '#446644'
    type: color
  spotlight-2--position--x:
    defaultValue:
      - 800
      - 800
      - -200
    type: position
  spotlight-2--position--y:
    defaultValue:
      - 800
      - 800
      - -200
    type: position
  spotlight-2--position--z:
    defaultValue:
      - 800
      - 800
      - -200
    type: position
  spotlight-3--color:
    defaultValue: '#000000'
    type: color
  spotlight-3--position--x:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-3--position--y:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  spotlight-3--position--z:
    defaultValue:
      - -500
      - 800
      - -500
    type: position
  electron--color:
    defaultValue: '#ffff33'
    type: color
  electron--opacity:
    defaultValue: 1
    type: range
  electron--scale:
    defaultValue: 1
    type: range
  icosa--scale:
    defaultValue: 1
    type: range
  dodeca--scale:
    defaultValue: 1
    type: range
  octa--scale:
    defaultValue: 1
    type: range
  octa--rotation--x:
    defaultValue: '0'
    type: rotation
  octa--rotation--y:
    defaultValue: 0
    type: rotation
  octa--rotation--z:
    defaultValue: 1
    type: rotation
  hexaWireframe--color:
    defaultValue: '#55ff55'
    type: color
  hexaWireframe--opacity:
    defaultValue: 1
    type: range
  hexaWireframe--linewidth:
    defaultValue: 1
    type: range
  icosaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaAxes--opacity:
    defaultValue: 0
    type: range
  icosaAxes--scale:
    defaultValue: 2
    type: range
  icosaAxes--linewidth:
    defaultValue: 1
    type: range
  dodecaAxes--color:
    defaultValue: '#aabb99'
    type: color
  dodecaAxes--opacity:
    defaultValue: 0
    type: range
  dodecaAxes--scale:
    defaultValue: 2
    type: range
  dodecaAxes--linewidth:
    defaultValue: 1
    type: range
  octaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  octaAxes--opacity:
    defaultValue: 0
    type: range
  octaAxes--scale:
    defaultValue: 2
    type: range
  octaAxes--linewidth:
    defaultValue: 1
    type: range
  tetraAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  tetraAxes--opacity:
    defaultValue: 0
    type: range
  tetraAxes--scale:
    defaultValue: 2
    type: range
  tetraAxes--linewidth:
    defaultValue: 1
    type: range
  hexaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  hexaAxes--opacity:
    defaultValue: 0
    type: range
  hexaAxes--scale:
    defaultValue: 2
    type: range
  hexaAxes--linewidth:
    defaultValue: 1
    type: range
filepath: config/style/builder/base.yml
