name: Nuclets
description: 'Highlight Nuclets by color'
filepath: config/themes/atom_builder/Nuclets.yml
settings:
  ambient--color:
    defaultValue: '#c9c9c9'
    type: color
  animation--speed:
    defaultValue: '10'
    type: range
  attachLines--linewidth:
    defaultValue: 1
    type: range
  attachLines--opacity:
    defaultValue: 0
    type: range
  attachLines--scale:
    defaultValue: 3
    type: range
  camera--perspective:
    defaultValue: 30
    type: range
  camera--position--x:
    defaultValue: 0
    type: position
  camera--position--x--az-slider:
    defaultValue: 0
    type: position
  camera--position--x-x--az-slider:
    defaultValue: 0
    type: position
  camera--position--x-y--az-slider:
    defaultValue: 0
    type: position
  camera--position--x-z--az-slider:
    defaultValue: 0
    type: position
  camera--position--y:
    defaultValue: 1200
    type: position
  camera--position--y--az-slider:
    defaultValue: 1200
    type: position
  camera--position--y-x--az-slider:
    defaultValue: 700
    type: position
  camera--position--y-y--az-slider:
    defaultValue: 700
    type: position
  camera--position--y-z--az-slider:
    defaultValue: 700
    type: position
  camera--position--z:
    defaultValue: -2000
    type: position
  camera--position--z--az-slider:
    defaultValue: -2000
    type: position
  camera--position--z-x--az-slider:
    defaultValue: -1500
    type: position
  camera--position--z-y--az-slider:
    defaultValue: -1500
    type: position
  camera--position--z-z--az-slider:
    defaultValue: -1500
    type: position
  deca--scale:
    defaultValue: 1
    type: range
  decaAxes--color:
    defaultValue: '#aabb99'
    type: color
  decaAxes--linewidth:
    defaultValue: 1
    type: range
  decaAxes--opacity:
    defaultValue: 0
    type: range
  decaAxes--scale:
    defaultValue: 2
    type: range
  decaFaceid--opacity:
    defaultValue: 0
    type: range
  decaFaceids--scale:
    defaultValue: 1
    type: range
  decaFaces--color:
    defaultValue: '#88cccc'
    type: color
  decaFaces--opacity:
    defaultValue: 0
    type: range
  decaVertexid--opacity:
    defaultValue: 0
    type: range
  decaVertexids--scale:
    defaultValue: 1
    type: range
  decaWireframe--color:
    defaultValue: '#00ff15'
    type: color
  decaWireframe--linewidth:
    defaultValue: '1'
    type: range
  decaWireframe--opacity:
    defaultValue: 1
    type: range
  decahedron--position--x:
    defaultValue: 0
    type: position
  decahedron--position--x--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--x-x--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--x-y--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--x-z--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--y:
    defaultValue: 0
    type: position
  decahedron--position--y--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--y-x--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--y-y--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--y-z--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--z:
    defaultValue: 0
    type: position
  decahedron--position--z--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--z-x--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--z-y--az-slider:
    defaultValue: 0
    type: position
  decahedron--position--z-z--az-slider:
    defaultValue: 0
    type: position
  decahedron--rotation--x:
    defaultValue: 0
    type: rotation
  decahedron--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--x-x--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--x-y--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--x-z--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--y:
    defaultValue: 0
    type: rotation
  decahedron--rotation--y--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--y-x--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--y-y--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--y-z--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--z:
    defaultValue: 0
    type: rotation
  decahedron--rotation--z--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--z-x--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--z-y--az-slider:
    defaultValue: 0
    type: rotation
  decahedron--rotation--z-z--az-slider:
    defaultValue: 0
    type: rotation
  dodeca--scale:
    defaultValue: '1.03'
    type: range
  dodecaAxes--color:
    defaultValue: '#aabb99'
    type: color
  dodecaAxes--linewidth:
    defaultValue: 1
    type: range
  dodecaAxes--opacity:
    defaultValue: 0
    type: range
  dodecaAxes--scale:
    defaultValue: 2
    type: range
  dodecaAxis--color:
    defaultValue: '#aabb99'
    type: color
  dodecaAxis--linewidth:
    defaultValue: 1
    type: range
  dodecaAxis--opacity:
    defaultValue: 0
    type: range
  dodecaFaceid--opacity:
    defaultValue: 0
    type: range
  dodecaFaceids--scale:
    defaultValue: 1
    type: range
  dodecaFaces--color:
    defaultValue: '#000000'
    type: color
  dodecaFaces--opacity:
    defaultValue: '0'
    type: range
  dodecaOut--scale:
    defaultValue: 1
    type: range
  dodecaOutAxes--color:
    defaultValue: '#aabb99'
    type: color
  dodecaOutAxes--linewidth:
    defaultValue: 1
    type: range
  dodecaOutAxes--opacity:
    defaultValue: 0
    type: range
  dodecaOutAxes--scale:
    defaultValue: 2
    type: range
  dodecaOutFaceid--opacity:
    defaultValue: 0
    type: range
  dodecaOutFaces--color:
    defaultValue: '#88cccc'
    type: color
  dodecaOutFaces--opacity:
    defaultValue: '0.02'
    type: range
  dodecaOutVertexid--opacity:
    defaultValue: 0
    type: range
  dodecaOutWireframe--color:
    defaultValue: '#00ffff'
    type: color
  dodecaOutWireframe--linewidth:
    defaultValue: 3
    type: range
  dodecaOutWireframe--opacity:
    defaultValue: '0'
    type: range
  dodecaVertexid--opacity:
    defaultValue: 0
    type: range
  dodecaVertexids--scale:
    defaultValue: 1
    type: range
  dodecaWireframe--color:
    defaultValue: '#9500ff'
    type: color
  dodecaWireframe--linewidth:
    defaultValue: '1'
    type: range
  dodecaWireframe--opacity:
    defaultValue: 1
    type: range
  dodecaWireframe--scale:
    defaultValue: 1
    type: range
  electron--color:
    defaultValue: '#ffff33'
    type: color
  electron--opacity:
    defaultValue: 1
    type: range
  electron--radius:
    type: range
    defaultValue: 5
  electron--scale:
    defaultValue: '0.87'
    type: range
  faces--opacity:
    defaultValue: '1'
    type: range
  faces-negative--color:
    defaultValue: '#fffd73'
    type: color
  faces-neutral--color:
    defaultValue: '#74ff74'
    type: color
  faces-positive--color:
    defaultValue: '#74fdff'
    type: color
  hexaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  hexaAxes--linewidth:
    defaultValue: 1
    type: range
  hexaAxes--opacity:
    defaultValue: 0
    type: range
  hexaAxes--scale:
    defaultValue: 2
    type: range
  hexaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  hexaAxis--linewidth:
    defaultValue: 1
    type: range
  hexaAxis--opacity:
    defaultValue: 0
    type: range
  hexaFace--color:
    defaultValue: '#88cccc'
    type: color
  hexaFace--opacity:
    defaultValue: 0
    type: range
  hexaFaceid--opacity:
    defaultValue: 0
    type: range
  hexaFaceids--scale:
    defaultValue: 1
    type: range
  hexaVertexid--opacity:
    defaultValue: 0
    type: range
  hexaVertexids--scale:
    defaultValue: 1
    type: range
  hexaWcireframe--color:
    defaultValue: '#55ff55'
    type: color
  hexaWcireframe--linewidth:
    defaultValue: 1
    type: range
  hexaWcireframe--opacity:
    defaultValue: 1
    type: range
  hexaWireframe--color:
    defaultValue: '#55ff55'
    type: color
  hexaWireframe--linewidth:
    defaultValue: 1
    type: range
  hexaWireframe--opacity:
    defaultValue: 1
    type: range
  hexaWireframe--scale:
    defaultValue: 1
    type: range
  icosa--scale:
    defaultValue: '1'
    type: range
  icosaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaAxes--linewidth:
    defaultValue: 1
    type: range
  icosaAxes--opacity:
    defaultValue: 0
    type: range
  icosaAxes--scale:
    defaultValue: 2
    type: range
  icosaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaAxis--linewidth:
    defaultValue: 1
    type: range
  icosaAxis--opacity:
    defaultValue: 0
    type: range
  icosaFaceid--opacity:
    defaultValue: 0
    type: range
  icosaFaceids--scale:
    defaultValue: 1
    type: range
  icosaFaces--color:
    defaultValue: '#019e04'
    type: color
  icosaFaces--opacity:
    defaultValue: '0'
    type: range
  icosaOut--scale:
    defaultValue: '1.53'
    type: range
  icosaOutAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  icosaOutAxes--linewidth:
    defaultValue: 1
    type: range
  icosaOutAxes--opacity:
    defaultValue: 0
    type: range
  icosaOutAxes--scale:
    defaultValue: 2
    type: range
  icosaOutFaceid--opacity:
    defaultValue: 0
    type: range
  icosaOutFaces--color:
    defaultValue: '#ccca88'
    type: color
  icosaOutFaces--opacity:
    defaultValue: '0'
    type: range
  icosaOutVertexid--opacity:
    defaultValue: 0
    type: range
  icosaOutWireframe--color:
    defaultValue: '#faff33'
    type: color
  icosaOutWireframe--linewidth:
    defaultValue: 3
    type: range
  icosaOutWireframe--opacity:
    defaultValue: '0'
    type: range
  icosaVertexid--opacity:
    defaultValue: 0
    type: range
  icosaVertexids--scale:
    defaultValue: 1
    type: range
  icosaWireframe--color:
    defaultValue: '#4fd5ce'
    type: color
  icosaWireframe--linewidth:
    defaultValue: '1'
    type: range
  icosaWireframe--opacity:
    defaultValue: '1'
    type: range
  icosaWireframe--scale:
    defaultValue: 1
    type: range
  nuclet--attachAngle:
    defaultValue: '5'
    type: range
  nucletAxes--linewidth:
    defaultValue: 1
    type: range
  nucletAxes--opacity:
    defaultValue: 0
    type: range
  nucletAxes--scale:
    defaultValue: 4
    type: range
  nucletInnerAxes--linewidth:
    defaultValue: 3
    type: range
  nucletInnerAxes--opacity:
    defaultValue: 0
    type: range
  nucletInnerAxes--scale:
    defaultValue: 3
    type: range
  nucletOuterAxes--linewidth:
    defaultValue: 5
    type: range
  nucletOuterAxes--opacity:
    defaultValue: 0
    type: range
  nucletOuterAxes--scale:
    defaultValue: 2
    type: range
  octa--rotation--x:
    defaultValue: 0
    type: rotation
  octa--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--x-x--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--x-y--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--x-z--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--y:
    defaultValue: 0
    type: rotation
  octa--rotation--y--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--y-x--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--y-y--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--y-z--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--z:
    defaultValue: 1
    type: rotation
  octa--rotation--z--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--z-x--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--z-y--az-slider:
    defaultValue: 0
    type: rotation
  octa--rotation--z-z--az-slider:
    defaultValue: 0
    type: rotation
  octa--scale:
    defaultValue: '1.07'
    type: range
  octaAexis--linewidth:
    defaultValue: 1
    type: range
  octaAexis--opacity:
    defaultValue: 0
    type: range
  octaAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  octaAxes--linewidth:
    defaultValue: 1
    type: range
  octaAxes--opacity:
    defaultValue: 0
    type: range
  octaAxes--scale:
    defaultValue: 2
    type: range
  octaAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  octaVertexid--opacity:
    defaultValue: 0
    type: range
  octaVertexids--scale:
    defaultValue: 1
    type: range
  octaWireframe--color:
    defaultValue: '#ffff00'
    type: color
  octaWireframe--linewidth:
    defaultValue: '2'
    type: range
  octaWireframe--opacity:
    defaultValue: 1
    type: range
  octaWireframe--scale:
    defaultValue: 1
    type: range
  plane--color:
    defaultValue: '#46414a'
    type: color
  plane--depth:
    defaultValue: 2000
    type: range
  plane--opacity:
    defaultValue: 1
    type: range
  plane--position--x:
    defaultValue: 0
    type: position
  plane--position--x--az-slider:
    defaultValue: 0
    type: position
  plane--position--x-x--az-slider:
    defaultValue: 0
    type: position
  plane--position--x-y--az-slider:
    defaultValue: 0
    type: position
  plane--position--x-z--az-slider:
    defaultValue: 0
    type: position
  plane--position--y:
    defaultValue: -400
    type: position
  plane--position--y--az-slider:
    defaultValue: -400
    type: position
  plane--position--y-x--az-slider:
    defaultValue: -200
    type: position
  plane--position--y-y--az-slider:
    defaultValue: -200
    type: position
  plane--position--y-z--az-slider:
    defaultValue: -200
    type: position
  plane--position--z:
    defaultValue: 0
    type: position
  plane--position--z--az-slider:
    defaultValue: 0
    type: position
  plane--position--z-x--az-slider:
    defaultValue: 0
    type: position
  plane--position--z-y--az-slider:
    defaultValue: 0
    type: position
  plane--position--z-z--az-slider:
    defaultValue: 0
    type: position
  plane--rotation--x:
    defaultValue: 0
    type: rotation
  plane--rotation--x--az-slider:
    defaultValue: 0
    type: rotation
  plane--rotation--x-x--az-slider:
    defaultValue: 0
    type: rotation
  plane--rotation--x-y--az-slider:
    defaultValue: 0
    type: rotation
  plane--rotation--x-z--az-slider:
    defaultValue: 0
    type: rotation
  plane--rotation--y:
    defaultValue: -180
    type: rotation
  plane--rotation--y--az-slider:
    defaultValue: -180
    type: rotation
  plane--rotation--y-x--az-slider:
    defaultValue: -180
    type: rotation
  plane--rotation--y-y--az-slider:
    defaultValue: -180
    type: rotation
  plane--rotation--y-z--az-slider:
    defaultValue: -180
    type: rotation
  plane--rotation--z:
    defaultValue: 1
    type: rotation
  plane--rotation--z--az-slider:
    defaultValue: 1
    type: rotation
  plane--rotation--z-x--az-slider:
    defaultValue: 1
    type: rotation
  plane--rotation--z-y--az-slider:
    defaultValue: 1
    type: rotation
  plane--rotation--z-z--az-slider:
    defaultValue: 1
    type: rotation
  plane--width:
    defaultValue: 2500
    type: range
  proton--opacity:
    defaultValue: '0.85'
    type: range
  proton--radius:
    type: range
    defaultValue: 50
  proton--scale:
    defaultValue: '1'
    type: range
  proton-beryllium--color:
    defaultValue: '#9e5e43'
    type: color
  proton-boron--color:
    defaultValue: '#76763b'
    type: color
  proton-capped--color:
    defaultValue: '#697881'
    type: color
  proton-carbon--color:
    defaultValue: '#346e7f'
    type: color
  proton-default--color:
    defaultValue: '#767676'
    type: color
  proton-final--color:
    defaultValue: '#8c8c8c'
    type: color
  proton-ghost--color:
    defaultValue: '#ac58ac'
    type: color
  proton-grow--color:
    defaultValue: '#3d5744'
    type: color
  proton-initial--color:
    defaultValue: '#346e7f'
    type: color
  proton-lithium--color:
    defaultValue: '#914747'
    type: color
  proton-neutral--color:
    defaultValue: '#437641'
    type: color
  proton-polar--color:
    defaultValue: '#454b5b'
    type: color
  proton-valence--color:
    defaultValue: '#534444'
    type: color
  protonVertexid--color:
    defaultValue: '#fc78fc'
    type: color
  protonVertexid--opacity:
    defaultValue: 0
    type: range
  protonVertexid--scale:
    defaultValue: 1
    type: range
  protons--scale:
    defaultValue: 1
    type: range
  renderer--color:
    defaultValue: '#084a65'
    type: color
  spotlight-1--color:
    defaultValue: '#978d97'
    type: color
  spotlight-1--position--x--az-slider:
    defaultValue: -500
    type: position
  spotlight-1--position--y--az-slider:
    defaultValue: 700
    type: position
  spotlight-1--position--z--az-slider:
    defaultValue: -300
    type: position
  spotlight-2--color:
    defaultValue: '#caf6f6'
    type: color
  spotlight-2--position--x--az-slider:
    defaultValue: 500
    type: position
  spotlight-2--position--y--az-slider:
    defaultValue: 700
    type: position
  spotlight-2--position--z--az-slider:
    defaultValue: 300
    type: position
  spotlight-3--color:
    defaultValue: '#c5c5a9'
    type: color
  spotlight-3--position--x--az-slider:
    defaultValue: 0
    type: position
  spotlight-3--position--y--az-slider:
    defaultValue: -700
    type: position
  spotlight-3--position--z--az-slider:
    defaultValue: -300
    type: position
  tetraAxes--color:
    defaultValue: '#ffbbcc'
    type: color
  tetraAxes--linewidth:
    defaultValue: 1
    type: range
  tetraAxes--opacity:
    defaultValue: 0
    type: range
  tetraAxes--scale:
    defaultValue: 2
    type: range
  tetraAxis--color:
    defaultValue: '#ffbbcc'
    type: color
  tetraAxis--linewidth:
    defaultValue: 1
    type: range
  tetraAxis--opacity:
    defaultValue: 0
    type: range
  tetraFaceid--opacity:
    defaultValue: 0
    type: range
  tetraFaceids--scale:
    defaultValue: '1.33'
    type: range
  tetraFaces--color:
    defaultValue: '#00fcff'
    type: color
  tetraFaces--opacity:
    defaultValue: '0'
    type: range
  tetraVertexid--opacity:
    defaultValue: 0
    type: range
  tetraVertexids--scale:
    defaultValue: 1
    type: range
  tetraWireframe--color:
    defaultValue: '#00ffdc'
    type: color
  tetraWireframe--linewidth:
    defaultValue: '1'
    type: range
  tetraWireframe--opacity:
    defaultValue: '1'
    type: range
  tetraWireframe--scale:
    defaultValue: 1
    type: range
  valence--diameter:
    defaultValue: 0.12
    type: range
  valence--opacity:
    defaultValue: '0'
    type: range
  valence--scale:
    defaultValue: '1'
    type: range
  valence-active--color:
    defaultValue: '#85223C'
    type: color
  valence-inactive--color:
    defaultValue: '#666666'
    type: color
