name: helium
position: {x: 0, y: 0, z: 0}
rotation: {x: 0, y: 0, z: 0}
allowmove: false
geoGroups:
  protons:
    allowrotate: false
    components:
      framework:
        shape: tetrahedron
        scale: 1.22
        protons:
          0:
            type: default
          1:
            type: default
          2:
            type: default
          3:
            type: default
  tetra:
    allowrotate: false
    components:
      solid:
        shape: tetrahedron
        scale: 1.094
        wireframe: true
        faces:
          0:
            type: valence
            attach: deca-left
            location: top-front
          1:
            type: isotope
            attach: deca-left
            location: top-middle
          2:
            type: isotope
            attach: deca-right
            location: top-middle
          3:
            type: valence
            attach: deca-right
            location: top-rear
      vertexids:
        shape: tetrahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: tetrahedron
        scale: 1.3
        faceids: true
