name: Carbon
weight: 6
geoGroups:
  protons:
    rotation:
      y: 90
    geometries:
      framework:
        shape: icosahedron
        scale: 1.9
        protons:
          0:
            type: grow
          1:
            type: grow
          2:
            type: grow
          3:
            type: grow
          4:
            type: valence
          5:
            type: valence
          6:
            type: valence
          7:
            type: valence
          8:
            type: polar
          9:
            type: polar
          10:
            type: polar
          11:
            type: polar
        valence:
          4:
            lock: [14, 15]
            rotation: {y: -36}
          5:
            lock: [16, 17]
            rotation: {y: 36}
          6:
            lock: [18, 19]
            rotation: {y: -36}
          7:
            lock: [12, 13]
            rotation: {y: 36}
  icosa:
    rotation:
      y: 90
    geometries:
      solid:
        shape: icosahedron
        scale: 1.37
        wireframe: true
        attachFaces: true
        faces:
          0:
            type: valence
            attach: -left
            location: top-front
          1:
            type: isotope
            attach: deca-left
            location: top-middle
          2:
            type: isotope
            attach: deca-right
            location: top-middle
          3:
            type: valence
            attach: deca-right
            location: top-rear
          4:
            type: valence
          5:
            type: valence
            attach: deca-left
            location: top-rear
          6:
            type: valence
            attach: deca-left
            location: bottom-front
          7:
            type: valence
          8:
            type: valence
            attach: deca-right
            location: bottom-rear
          9:
            type: valence
            attach: deca-right
            location: top-front
          10:
            type: valence
          11:
            type: isotope
          12:
            type: isotope
          13:
            type: valence
          14:
            type: valence
          15:
            type: valence
            attach: deca-left
            location: bottom-rear
          16:
            type: valence
          17:
            type: valence
          18:
            type: valence
            attach: deca-right
            location: bottom-front
          19:
            type: valence
      axes:
        shape: icosahedron
        axes:
          scale: 3
          vertices:
            - [0, 11]
            - [1,  8]
            - [2,  9]
            - [3, 10]
            - [4,  6]
            - [5,  7]
      vertexids:
        shape: icosahedron
        scale: 1.55
        vertexids: true
      faceids:
        shape: icosahedron
        scale: 1.3
        faceids: true

  dodeca:
    geometries:
      solid:
        shape: dodecahedron
        scale: 1.31
        wireframe: true
        faces: true
      axes:
        shape: dodecahedron
        axes:
          scale: 3
          vertices:
            - [0, 13]
            - [1, 12]
            - [2, 11]
            - [3, 10]
            - [4, 14]
            - [5, 17]
            - [6, 18]
            - [7, 19]
            - [8, 15]
            - [9, 16]
      vertexids:
        shape: dodecahedron
        scale: 1.3
        vertexids: true
      faceids:
        shape: dodecahedron
        scale: 1.5
        faceids: true

  octa:
    geometries:
      framework:
        shape: octahedron
        scale: 1.25
        electrons: 
          0:
            type: normal
          1:
            type: normal
          2:
            type: normal
          3:
            type: normal
          4:
            type: normal
          5:
            type: normal
        wireframe: true
      axes:
        shape: octahedron
        axes:
          scale: 3
          vertices:
            - [0, 1]
            - [2, 3]
            - [4, 5]
      vertexids:
        shape: octahedron
        scale: 1.3
        vertexids: true
